[build-system]
requires = [ "hatchling>=1.24.2", "hatch-vcs>=0.3.0",]
build-backend = "hatchling.build"

[project]
name = "shared"
version = "0.0.1"
description = "Shared modules and utilities"
readme = "README.md"
requires-python = ">=3.12"
keywords = []
classifiers = [ "Development Status :: 3 - Alpha", "Intended Audience :: Developers", "License :: OSI Approved :: MIT License", "Programming Language :: Python :: 3.11", "Programming Language :: Python :: 3.12",]
dependencies = []

[[project.authors]]
name = "Zachary Ernst"
email = "zac.ernst@gmail.com"

[[project.maintainers]]
name = "Zachary Ernst"
email = "zac.ernst@gmail.com"

[project.license]
file = "LICENSE.txt"

[project.optional-dependencies]
dev = [ "hatch>=1.12.0,<2.0.0",]

[project.urls]
Homepage = "https://github.com/zacernst/pycypher-nmetl"

[project.scripts]

[tool.ruff]
exclude = [ ".bzr", ".direnv", ".eggs", ".git", ".git-rewrite", ".hg", ".ipynb_checkpoints", ".mypy_cache", ".nox", ".pants.d", ".pyenv", ".pytest_cache", ".pytype", ".ruff_cache", ".svn", ".tox", ".venv", ".vscode", "__pypackages__", "_build", "buck-out", "build", "dist", "node_modules", "site-packages", "venv",]
line-length = 79
indent-width = 4
target-version = "py313"

[tool.coverage.report]
exclude_also = [ "def tree", "def print_tree", "def __repr__", "if self.debug:", "if settings.DEBUG", "raise AssertionError", "raise NotImplementedError", "if 0:", "if __name__ == .__main__.:", "if TYPE_CHECKING:", "class .*\\bProtocol\\):", "@(abc\\.)?abstractmethod",]

[tool.coverage.run]
omit = [
    # omit anything in a .local directory anywhere
    "*/.local/*",
    "*/fastopendata/src/fastopendata/*",
    "/*.py",
    "*/filter_us_nodes.py"
    ]

[tool.pytest.ini_options]
addopts = ""
testpaths = [ "tests",]
