stages:
  state_county_tract_puma:
    cmd: wget https://www2.census.gov/geo/docs/maps-data/data/rel2020/2020_Census_Tract_to_2020_PUMA.txt -O - | sed $'1s/^\uFEFF//' > /Users/zernst/git/pycypher-nmetl/packages/fastopendata/raw_data/state_county_tract_puma.csv
    outs:
    - packages/fastopendata/raw_data/state_county_tract_puma.csv
  census_pus:
    cmd: wget https://www2.census.gov/programs-surveys/acs/data/pums/2023/1-Year/csv_pus.zip
      -O 
      /Users/zernst/git/pycypher-nmetl/packages/fastopendata/raw_data/csv_pus.zip
    outs:
    - packages/fastopendata/raw_data/csv_pus.zip
  unzip_psam:
    cmd: unzip -o 
      /Users/zernst/git/pycypher-nmetl/packages/fastopendata/raw_data/csv_pus.zip
      -d /Users/zernst/git/pycypher-nmetl/packages/fastopendata/raw_data/
    deps:
    - packages/fastopendata/raw_data/csv_pus.zip
    outs:
    - packages/fastopendata/raw_data/psam_pusa.csv
    - packages/fastopendata/raw_data/psam_pusb.csv
  combine_psam:
    cmd: (cat 
      /Users/zernst/git/pycypher-nmetl/packages/fastopendata/raw_data/psam_pusa.csv
      > 
      /Users/zernst/git/pycypher-nmetl/packages/fastopendata/raw_data/psam_pus.csv
      && cat 
      /Users/zernst/git/pycypher-nmetl/packages/fastopendata/raw_data/psam_pusb.csv
      | tail +2 >> 
      /Users/zernst/git/pycypher-nmetl/packages/fastopendata/raw_data/psam_pus.csv)
    deps:
    - packages/fastopendata/raw_data/psam_pusa.csv
    - packages/fastopendata/raw_data/psam_pusb.csv
    outs:
    - packages/fastopendata/raw_data/psam_pus.csv
  split_psam_to_housing_and_individual:
    cmd: head -1 packages/fastopendata/raw_data/psam_pus.csv > packages/fastopendata/raw_data/psam_2023_individual.csv
      && grep 2023GQ packages/fastopendata/raw_data/psam_pus.csv >> packages/fastopendata/raw_data/psam_2023_individual.csv
      && head -1 packages/fastopendata/raw_data/psam_pus.csv > packages/fastopendata/raw_data/psam_2023_housing.csv
      && grep 2023HU packages/fastopendata/raw_data/psam_pus.csv >> packages/fastopendata/raw_data/psam_2023_housing.csv
    deps:
    - packages/fastopendata/raw_data/psam_pus.csv
    outs:
    - packages/fastopendata/raw_data/psam_2023_housing.csv
    - packages/fastopendata/raw_data/psam_2023_individual.csv
  census_pus_5_year:
    cmd: wget https://www2.census.gov/programs-surveys/acs/data/pums/2023/5-Year/csv_pus.zip
      -O 
      /Users/zernst/git/pycypher-nmetl/packages/fastopendata/raw_data/csv_pus_5_year.zip
    outs:
    - packages/fastopendata/raw_data/csv_pus_5_year.zip
  osm:
    cmd: wget https://download.geofabrik.de/north-america/us-latest.osm.pbf -O 
      /Users/zernst/git/pycypher-nmetl/packages/fastopendata/raw_data/us-latest.osm.pbf
    outs:
    - packages/fastopendata/raw_data/us-latest.osm.pbf
  united_states_nodes_csv:
    cmd: python 
      /Users/zernst/git/pycypher-nmetl/packages/fastopendata/src/fastopendata/extract_osm_nodes.py
    deps:
    - packages/fastopendata/raw_data/us-latest.osm.pbf
    outs:
    - packages/fastopendata/raw_data/united_states_nodes.csv
  census_block_shape_files:
    cmd: /bin/bash -c ./packages/fastopendata/src/fastopendata/block_shape_files.sh
    outs:
    - packages/fastopendata/raw_data/combined.shp
  download_wikidata:
    cmd: wget https://dumps.wikimedia.org/wikidatawiki/entities/latest-all.json.bz2 -O 
      /Users/zernst/git/pycypher-nmetl/packages/fastopendata/raw_data/latest-all.json.bz2
    outs:
    - packages/fastopendata/raw_data/latest-all.json.bz2
  extract_entities_from_wikidata:
    cmd: cat /Users/zernst/git/pycypher-nmetl/packages/fastopendata/raw_data/latest-all.json.bz2| pv -s `ls -l /Users/zernst/git/pycypher-nmetl/packages/fastopendata/raw_data/latest-all.json.bz2 | awk '{print $5}'` | pbunzip2 -c | grep latitude | gzip -9 > /Users/zernst/git/pycypher-nmetl/packages/fastopendata/raw_data/entities_with_lat_long.json.gz
    deps:
    - packages/fastopendata/raw_data/latest-all.json.bz2
    outs:
    - packages/fastopendata/raw_data/entities_with_lat_long.json.gz
  download_pums_5_year:
    cmd: wget -P /Users/zernst/git/pycypher-nmetl/packages/fastopendata/raw_data/ -e robots=off -nH --recursive -np https://www2.census.gov/programs-surveys/acs/data/pums/2023/5-Year/ && /bin/bash -c /Users/zernst/git/pycypher-nmetl/packages/fastopendata/raw_pums_5_year.sh
    outs:
    - /Users/zernst/git/pycypher-nmetl/packages/fastopendata/raw_data/psam_p.csv
    - /Users/zernst/git/pycypher-nmetl/packages/fastopendata/raw_data/psam_h.csv
  download_puma_shapefiles:
    cmd: wget -P /Users/zernst/git/pycypher-nmetl/packages/fastopendata/raw_data/ -e robots=off -nH --recursive -np https://www2.census.gov/geo/tiger/TIGER2024/PUMA20/ && /bin/bash -c /Users/zernst/git/pycypher-nmetl/packages/fastopendata/src/fastopendata/puma_shape_files.sh && uv run /Users/zernst/git/pycypher-nmetl/packages/fastopendata/src/fastopendata/concatenate_puma_shape_files.py
    outs:
    - ./packages/fastopendata/raw_data/puma_combined.shp
