{
 "title": "Raw data items queued",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(solutions_histogram_count{job=\"nmetl\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CheckFactAgainstTriggers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "irate(CheckFactAgainstTriggersQueueProcessor_total{job=\"nmetl\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Facts appended rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(facts_appended_total{job=\"nmetl\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Facts appended",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "facts_appended_total{job=\"nmetl\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Seconds spent in FDB range iterator",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(seconds_in_iterator_sum{job=\"nmetl\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lists of raw data facts queued",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "irate(raw_data_results_total{job=\"nmetl\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Keys scanned per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(keys_scanned_histogram_sum{job=\"nmetl\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TriggeredLookupProcessor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(TriggeredLookupProcessor_total{job=\"nmetl\"}[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FactGeneratedQueueProcessor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "irate(FactGeneratedQueueProcessor_total{job=\"nmetl\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}