scrape_configs:
  - job_name: 'pycypher-app'
    static_configs:
      - targets: ['localhost:8000']
  - job_name: 'node-system'
    static_configs:
      - targets: ['localhost:9100']
  - job_name: 'dask-scheduler'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8787']  # Replace with your scheduler address

