"""Pydantic models for openCypher AST nodes.

This package provides strongly-typed Pydantic models for the Abstract Syntax Tree
generated by the grammar parser. It includes utilities for converting dict-based
ASTs to typed models, traversing, modifying, and pretty-printing the AST.

Important Notes:
    - All variable references are represented as Variable instances (not strings)
    - This includes variables in patterns (NodePattern, RelationshipPattern),
      comprehensions (ListComprehension, PatternComprehension), quantifiers,
      and all other binding contexts
    - The ASTConverter automatically wraps string variable names in Variable
      instances during conversion

Usage::

    from pycypher.grammar_parser import GrammarParser
    from pycypher.ast_models import ASTConverter

    parser = GrammarParser()
    parse_tree = parser.parse("MATCH (n:Person) RETURN n")
    raw_ast = parser.transformer.transform(parse_tree)

    converter = ASTConverter()
    typed_ast = converter.convert(raw_ast)

    # Traverse the AST
    for node in typed_ast.traverse():
        print(f"Node type: {node.__class__.__name__}")

    # Pretty print
    print(typed_ast.pretty())

    # Access variable names
    from pycypher.ast_models import NodePattern, Variable
    node = NodePattern(variable=Variable(name="n"), labels=["Person"])
    print(node.variable.name)  # "n"

The module is split into four domain submodules for maintainability:

- :mod:`pycypher.ast_models.core` — Base classes, enums, validation framework
- :mod:`pycypher.ast_models.clauses` — Query structure, clauses, and patterns
- :mod:`pycypher.ast_models.expressions` — All expression types
- :mod:`pycypher.ast_models.validation` — Validation functions and utilities
"""

from __future__ import annotations

from typing import Any

# Core: base classes, enums, validation framework
from pycypher.ast_models.core import (
    Algebraizable,
    ASTNode,
    JoinType,
    random_hash,
    RelationshipDirection,
    ValidationIssue,
    ValidationResult,
    ValidationSeverity,
)

# Clauses: query structure, clauses, and patterns
from pycypher.ast_models.clauses import (
    AddAllPropertiesItem,
    Call,
    Clause,
    Create,
    Delete,
    Foreach,
    Match,
    Merge,
    NodePattern,
    OrderByItem,
    PathLength,
    Pattern,
    PatternIntersection,
    PatternPath,
    Query,
    RelationshipPattern,
    Remove,
    RemoveItem,
    Return,
    ReturnAll,
    ReturnItem,
    Set,
    SetAllPropertiesItem,
    SetItem,
    SetLabelsItem,
    SetPropertyItem,
    UnionQuery,
    Unwind,
    With,
    YieldItem,
)

# Expressions: all expression types
from pycypher.ast_models.expressions import (
    AllShortestPaths,
    And,
    Arithmetic,
    BinaryExpression,
    BooleanLiteral,
    CaseExpression,
    Comparison,
    CountStar,
    Exists,
    Expression,
    FloatLiteral,
    FunctionInvocation,
    IndexLookup,
    IntegerLiteral,
    LabelPredicate,
    ListComprehension,
    ListLiteral,
    Literal,
    MapElement,
    MapLiteral,
    MapProjection,
    Not,
    NullCheck,
    NullLiteral,
    Or,
    Parameter,
    PatternComprehension,
    PropertyLookup,
    Quantifier,
    Reduce,
    ShortestPath,
    Slicing,
    StringLiteral,
    StringPredicate,
    Unary,
    Variable,
    WhenClause,
    Xor,
)

# Validation: validation functions and utilities
from pycypher.ast_models.validation import (
    _check_contradictory_comparisons,
    _collect_defined_variables,
    _collect_definition_ids,
    _collect_referenced_variables,
    _validate_delete_without_detach,
    _validate_expensive_patterns,
    _validate_missing_labels,
    _validate_return_all_with_limit,
    _validate_undefined_variables,
    _validate_unreachable_conditions,
    _validate_unused_variables,
    convert_ast,
    extract_referenced_variables,
    find_nodes,
    print_ast,
    traverse_ast,
    validate_ast,
)

# ============================================================================
# Rebuild Pydantic models to resolve cross-module forward references.
# clauses.py uses Expression/Variable (from expressions.py) and
# expressions.py uses Pattern/Query (from clauses.py) as string annotations.
# After all modules are imported, we must rebuild so Pydantic can resolve them.
# ============================================================================

def _rebuild_models() -> None:
    """Rebuild all Pydantic models to resolve forward references."""
    from pycypher.ast_models import clauses as _c
    from pycypher.ast_models import expressions as _e

    # Collect all model classes from both modules
    _namespace = {}
    for _mod in (_c, _e):
        for _name in dir(_mod):
            _obj = getattr(_mod, _name)
            if isinstance(_obj, type) and issubclass(_obj, ASTNode):
                _namespace[_name] = _obj

    # Rebuild clause models that reference expression types
    for _name in dir(_c):
        _obj = getattr(_c, _name)
        if isinstance(_obj, type) and issubclass(_obj, ASTNode):
            try:
                _obj.model_rebuild(_types_namespace=_namespace)
            except Exception:  # noqa: BLE001
                pass

    # Rebuild expression models that reference clause types
    for _name in dir(_e):
        _obj = getattr(_e, _name)
        if isinstance(_obj, type) and issubclass(_obj, ASTNode):
            try:
                _obj.model_rebuild(_types_namespace=_namespace)
            except Exception:  # noqa: BLE001
                pass

_rebuild_models()
del _rebuild_models

# ============================================================================
# AST Converter — extracted to pycypher.ast_converter
# Re-exported here for backward compatibility via __getattr__ lazy loading.
# This avoids a circular import: ast_converter imports ast_models at the
# module level, so ast_models must not import ast_converter eagerly.
# ============================================================================

_CONVERTER_REEXPORTS: dict[str, str] = {
    "ASTConverter": "ASTConverter",
    "_friendly_parse_error": "_friendly_parse_error",
    "_parse_cypher_cached": "_parse_cypher_cached",
}


def __getattr__(name: str) -> Any:
    if name in _CONVERTER_REEXPORTS:
        import pycypher.ast_converter as _conv

        return getattr(_conv, _CONVERTER_REEXPORTS[name])
    msg = f"module {__name__!r} has no attribute {name!r}"
    raise AttributeError(msg)


__all__ = [
    # Core
    "ASTNode",
    "Algebraizable",
    "JoinType",
    "RelationshipDirection",
    "ValidationIssue",
    "ValidationResult",
    "ValidationSeverity",
    "random_hash",
    # Clauses
    "AddAllPropertiesItem",
    "Call",
    "Clause",
    "Create",
    "Delete",
    "Foreach",
    "Match",
    "Merge",
    "NodePattern",
    "OrderByItem",
    "PathLength",
    "Pattern",
    "PatternIntersection",
    "PatternPath",
    "Query",
    "RelationshipPattern",
    "Remove",
    "RemoveItem",
    "Return",
    "ReturnAll",
    "ReturnItem",
    "Set",
    "SetAllPropertiesItem",
    "SetItem",
    "SetLabelsItem",
    "SetPropertyItem",
    "UnionQuery",
    "Unwind",
    "With",
    "YieldItem",
    # Expressions
    "AllShortestPaths",
    "And",
    "Arithmetic",
    "BinaryExpression",
    "BooleanLiteral",
    "CaseExpression",
    "Comparison",
    "CountStar",
    "Exists",
    "Expression",
    "FloatLiteral",
    "FunctionInvocation",
    "IndexLookup",
    "IntegerLiteral",
    "LabelPredicate",
    "ListComprehension",
    "ListLiteral",
    "Literal",
    "MapElement",
    "MapLiteral",
    "MapProjection",
    "Not",
    "NullCheck",
    "NullLiteral",
    "Or",
    "Parameter",
    "PatternComprehension",
    "PropertyLookup",
    "Quantifier",
    "Reduce",
    "ShortestPath",
    "Slicing",
    "StringLiteral",
    "StringPredicate",
    "Unary",
    "Variable",
    "WhenClause",
    "Xor",
    # Validation/Utilities
    "convert_ast",
    "extract_referenced_variables",
    "find_nodes",
    "print_ast",
    "traverse_ast",
    "validate_ast",
]
