"""Pydantic models for openCypher AST nodes.

This module provides strongly-typed Pydantic models for the Abstract Syntax Tree
generated by the grammar parser. It includes utilities for converting dict-based
ASTs to typed models, traversing, modifying, and pretty-printing the AST.

Important Notes:
    - All variable references are represented as Variable instances (not strings)
    - This includes variables in patterns (NodePattern, RelationshipPattern),
      comprehensions (ListComprehension, PatternComprehension), quantifiers,
      and all other binding contexts
    - The ASTConverter automatically wraps string variable names in Variable
      instances during conversion

Usage::

    from pycypher.grammar_parser import GrammarParser
    from pycypher.ast_models import ASTConverter

    parser = GrammarParser()
    parse_tree = parser.parse("MATCH (n:Person) RETURN n")
    raw_ast = parser.transformer.transform(parse_tree)

    converter = ASTConverter()
    typed_ast = converter.convert(raw_ast)

    # Traverse the AST
    for node in typed_ast.traverse():
        print(f"Node type: {node.__class__.__name__}")

    # Pretty print
    print(typed_ast.pretty())

    # Access variable names
    from pycypher.ast_models import NodePattern, Variable
    node = NodePattern(variable=Variable(name="n"), labels=["Person"])
    print(node.variable.name)  # "n"
"""

from __future__ import annotations

import hashlib
import secrets
from abc import ABC
from enum import StrEnum
from typing import TYPE_CHECKING, Any, cast

from pydantic import BaseModel, ConfigDict, Field

if TYPE_CHECKING:
    from collections.abc import Callable, Iterator


def random_hash() -> str:
    """Generate a cryptographically secure random hash string for column naming.

    Creates a unique identifier using cryptographically secure random bytes
    and SHA256 hashing. Used to generate collision-resistant column names
    during algebraic operations.

    Returns:
        str: A 64-character hexadecimal hash string (SHA256 digest).

    Security:
        - Uses secrets.token_bytes() for cryptographically secure randomness
        - Uses SHA256 instead of broken MD5 hash function
        - 32 bytes of entropy provide 2^256 possible values

    """
    # Generate 32 bytes of cryptographically secure random data
    # This provides 256 bits of entropy (2^256 possible values)
    random_bytes = secrets.token_bytes(32)

    # Use SHA256 instead of broken MD5
    return hashlib.sha256(random_bytes).hexdigest()


class RelationshipDirection(StrEnum):
    """Enumeration of relationship directions in graph patterns.

    Attributes:
        LEFT: Left-directed relationship (e.g., <-[:REL]-).
        RIGHT: Right-directed relationship (e.g., -[:REL]->).
        UNDIRECTED: Undirected relationship (e.g., -[:REL]-).

    """

    LEFT = "<-"
    RIGHT = "->"
    UNDIRECTED = "-"  # We won't support this right away


class JoinType(StrEnum):
    """Enumeration of supported SQL join types.

    Attributes:
        INNER: Inner join - returns only matching rows from both tables.
        LEFT: Left outer join - returns all rows from left table.
        RIGHT: Right outer join - returns all rows from right table.
        FULL: Full outer join - returns all rows from both tables.

    """

    INNER = "INNER"
    LEFT = "LEFT"
    RIGHT = "RIGHT"
    FULL = "FULL"


# ============================================================================
# Validation Framework
# ============================================================================


class ValidationSeverity(StrEnum):
    """Severity levels for validation issues."""

    ERROR = "error"  # Query will likely fail or produce wrong results
    WARNING = "warning"  # Query will work but may have performance/correctness issues
    INFO = "info"  # Suggestions for improvement


class ValidationIssue(BaseModel):
    """A single validation issue found in the AST."""

    severity: ValidationSeverity
    message: str
    node_type: Any | None = None  # Can be string or ASTNode
    suggestion: Any | None = None  # Can be string or other types
    node: Any | None = None  # For compatibility with tests
    code: str | None = None  # For compatibility with tests

    model_config = ConfigDict(arbitrary_types_allowed=True)

    def __init__(
        self,
        severity: ValidationSeverity | dict | None = None,
        message: str | None = None,
        node: Any | None = None,
        code: str | None = None,
        **kwargs: Any,
    ) -> None:
        """Initialize ValidationIssue with positional or keyword arguments."""
        # If first argument is dict and message is None, Pydantic is calling with dict
        match severity:
            case dict():
                super().__init__(**severity)
            case _ if severity is not None or message is not None:
                # Positional or mixed arguments - convert to kwargs
                if severity is not None:
                    kwargs["severity"] = severity
                if message is not None:
                    kwargs["message"] = message
                if node is not None:
                    kwargs["node"] = node
                if code is not None:
                    kwargs["code"] = code
                super().__init__(**kwargs)
            case _:
                # All keyword arguments
                super().__init__(**kwargs)

    def __str__(self) -> str:
        parts = [f"[{self.severity.value.upper()}] {self.message}"]
        if self.node_type:
            parts.append(f" (in {self.node_type})")
        if self.suggestion:
            parts.append(f"\n  💡 {self.suggestion}")
        return "".join(parts)

    def __repr__(self) -> str:
        """String representation for debugging."""
        node_info = f" in {self.node.__class__.__name__}" if self.node else ""
        code_info = f" [{self.code}]" if self.code else ""
        return f"{self.severity.value.upper()}{code_info}: {self.message}{node_info}"


class ValidationResult(BaseModel):
    """Result of validating an AST."""

    issues: list[ValidationIssue] = Field(default_factory=list)

    @property
    def has_errors(self) -> bool:
        """Check if there are any error-level issues."""
        return any(
            issue.severity == ValidationSeverity.ERROR for issue in self.issues
        )

    @property
    def has_warnings(self) -> bool:
        """Check if there are any warning-level issues."""
        return any(
            issue.severity == ValidationSeverity.WARNING
            for issue in self.issues
        )

    @property
    def is_valid(self) -> bool:
        """Check if AST is valid (no errors)."""
        return not self.has_errors

    @property
    def errors(self) -> list[ValidationIssue]:
        """Get only error-level issues."""
        return [
            i for i in self.issues if i.severity == ValidationSeverity.ERROR
        ]

    @property
    def warnings(self) -> list[ValidationIssue]:
        """Get only warning-level issues."""
        return [
            i for i in self.issues if i.severity == ValidationSeverity.WARNING
        ]

    @property
    def infos(self) -> list[ValidationIssue]:
        """Get only info-level issues."""
        return [
            i for i in self.issues if i.severity == ValidationSeverity.INFO
        ]

    def add_issue(
        self,
        severity: ValidationSeverity,
        message: str,
        node_type: str | None = None,
        suggestion: str | None = None,
        node: Any | None = None,
        code: str | None = None,
    ) -> None:
        """Add a validation issue with the given severity.

        General-purpose method for recording validation issues. For
        convenience, use ``add_error``, ``add_warning``, or ``add_info``
        to add issues at a predetermined severity level.

        Args:
            severity: The severity level of the issue.
            message: Human-readable description of the validation problem.
            node_type: Optional AST node type name where the issue occurred.
            suggestion: Optional suggested fix or corrective action.
            node: Optional reference to the AST node that triggered the issue.
            code: Optional machine-readable issue identifier for programmatic
                handling.

        """
        self.issues.append(
            ValidationIssue(
                severity=severity,
                message=message,
                node_type=node_type,
                suggestion=suggestion,
                node=node,
                code=code,
            ),
        )

    def add_error(
        self,
        message: str,
        node_type: str | None = None,
        suggestion: str | None = None,
        node: Any | None = None,
        code: str | None = None,
    ) -> None:
        """Add an error-level validation issue.

        Convenience wrapper around :meth:`add_issue` that sets severity to
        :attr:`ValidationSeverity.ERROR`. Errors indicate problems that make
        the query invalid and must be resolved before execution.

        Args:
            message: Human-readable description of the validation error.
            node_type: Optional AST node type name where the error occurred.
            suggestion: Optional suggested fix or corrective action.
            node: Optional reference to the AST node that triggered the error.
            code: Optional machine-readable issue identifier for programmatic
                handling.

        """
        self.issues.append(
            ValidationIssue(
                severity=ValidationSeverity.ERROR,
                message=message,
                node_type=node_type,
                suggestion=suggestion,
                node=node,
                code=code,
            ),
        )

    def add_warning(
        self,
        message: str,
        node_type: str | None = None,
        suggestion: str | None = None,
        node: Any | None = None,
        code: str | None = None,
    ) -> None:
        """Add a warning-level validation issue.

        Convenience wrapper around :meth:`add_issue` that sets severity to
        :attr:`ValidationSeverity.WARNING`. Warnings indicate potential
        problems that do not prevent execution but may produce unexpected
        results.

        Args:
            message: Human-readable description of the validation warning.
            node_type: Optional AST node type name where the warning occurred.
            suggestion: Optional suggested fix or corrective action.
            node: Optional reference to the AST node that triggered the warning.
            code: Optional machine-readable issue identifier for programmatic
                handling.

        """
        self.issues.append(
            ValidationIssue(
                severity=ValidationSeverity.WARNING,
                message=message,
                node_type=node_type,
                suggestion=suggestion,
                node=node,
                code=code,
            ),
        )

    def add_info(
        self,
        message: str,
        node_type: str | None = None,
        suggestion: str | None = None,
        node: Any | None = None,
        code: str | None = None,
    ) -> None:
        """Add an informational validation issue.

        Convenience wrapper around :meth:`add_issue` that sets severity to
        :attr:`ValidationSeverity.INFO`. Informational issues are
        non-actionable observations about query structure, useful for
        debugging or optimization hints.

        Args:
            message: Human-readable description of the observation.
            node_type: Optional AST node type name relevant to the observation.
            suggestion: Optional suggested improvement or optimization.
            node: Optional reference to the AST node related to the observation.
            code: Optional machine-readable issue identifier for programmatic
                handling.

        """
        self.issues.append(
            ValidationIssue(
                severity=ValidationSeverity.INFO,
                message=message,
                node_type=node_type,
                suggestion=suggestion,
                node=node,
                code=code,
            ),
        )

    def __bool__(self) -> bool:
        """True if validation passed (no errors)."""
        return self.is_valid

    def __str__(self) -> str:
        if not self.issues:
            return "Validation passed: No issues found"

        status = "passed" if self.is_valid else "failed"
        lines = [f"Validation {status} with {len(self.issues)} issue(s):"]
        for i, issue in enumerate(self.issues, 1):
            lines.append(f"  {i}. {issue}")
        return "\n".join(lines)


# ============================================================================
# Base Classes
# ============================================================================


class ASTNode(BaseModel, ABC):
    """Base class for all AST nodes."""

    model_config = ConfigDict(arbitrary_types_allowed=True)

    def validate_ast(self, strict: bool = False) -> ValidationResult:
        """Validate this AST node and its children.

        Args:
            strict: If True, treat warnings as errors.

        Returns:
            ValidationResult containing verification details.

        """
        return validate_ast(self, strict)

    def traverse(self, depth: int = 0) -> Iterator[ASTNode]:
        """Traverse the AST depth-first, yielding all nodes.

        Args:
            depth: Current depth in the tree (used internally).

        Yields:
            ASTNode: Each node in the tree.

        Raises:
            SecurityError: If traversal exceeds ``MAX_QUERY_NESTING_DEPTH``.

        """
        from pycypher.config import MAX_QUERY_NESTING_DEPTH

        if depth > MAX_QUERY_NESTING_DEPTH:
            from pycypher.exceptions import SecurityError

            msg = (
                f"AST traversal exceeded maximum nesting depth "
                f"({MAX_QUERY_NESTING_DEPTH}). The query is too deeply "
                f"nested. Adjust PYCYPHER_MAX_QUERY_NESTING_DEPTH to increase."
            )
            raise SecurityError(msg)

        yield self
        for child in self._get_children():
            if child is not None:
                yield from child.traverse(depth + 1)

    def find_all(
        self,
        predicate: type | Callable[[ASTNode], bool],
    ) -> list[ASTNode]:
        """Find all nodes matching a predicate or type.

        Args:
            predicate: Either a type to match or a callable predicate function

        Returns:
            List of matching nodes

        """
        if callable(predicate) and not isinstance(predicate, type):
            return [node for node in self.traverse() if predicate(node)]
        return [
            node for node in self.traverse() if isinstance(node, predicate)
        ]

    def find_first(
        self,
        predicate: type | Callable[[ASTNode], bool],
    ) -> ASTNode | None:
        """Find the first node matching a predicate or type.

        Args:
            predicate: Either a type to match or a callable predicate function

        Returns:
            First matching node or None

        """
        if callable(predicate) and not isinstance(predicate, type):
            for node in self.traverse():
                if predicate(node):
                    return node
        else:
            for node in self.traverse():
                if isinstance(node, predicate):
                    return node
        return None

    def _get_children(self) -> list[ASTNode]:
        """Get all child nodes. Override in subclasses."""
        children: list[ASTNode] = []

        def collect(value: Any) -> None:
            """Recursively collect ASTNode children from a field value."""
            match value:
                case ASTNode():
                    children.append(value)
                case list() | tuple():
                    for item in value:
                        collect(item)
                case dict():
                    for item in value.values():
                        collect(item)

        for field_value in self.__dict__.values():
            collect(field_value)

        return children

    def pretty(self, indent: int = 0) -> str:
        """Pretty print the AST node.

        Args:
            indent: Current indentation level

        Returns:
            Formatted string representation

        """
        prefix = "  " * indent
        lines = [f"{prefix}{self.__class__.__name__}"]

        for field_name, field_value in self.__dict__.items():
            match field_value:
                case None:
                    continue
                case ASTNode():
                    lines.append(f"{prefix}  {field_name}:")
                    lines.append(field_value.pretty(indent + 2))
                case list() if field_value:
                    if all(isinstance(item, ASTNode) for item in field_value):
                        lines.append(f"{prefix}  {field_name}: [")
                        for item in field_value:
                            lines.append(item.pretty(indent + 2))
                        lines.append(f"{prefix}  ]")
                    else:
                        lines.append(f"{prefix}  {field_name}: {field_value}")
                case _ if (
                    not isinstance(field_value, (dict, list)) or field_value
                ):
                    lines.append(f"{prefix}  {field_name}: {field_value}")

        return "\n".join(lines)

    def to_dict(self) -> dict[str, Any]:
        """Convert back to dictionary representation."""
        result: dict[str, Any] = {"type": self.__class__.__name__}

        for field_name, field_value in self.__dict__.items():
            match field_value:
                case None:
                    continue
                case ASTNode():
                    result[field_name] = field_value.to_dict()
                case list():
                    result[field_name] = [
                        item.to_dict() if isinstance(item, ASTNode) else item
                        for item in field_value
                    ]
                case _:
                    result[field_name] = field_value

        return result

    def clone(self) -> ASTNode:
        """Create a deep copy of this node."""
        return self.__class__(**self.to_dict())

    def cypher_validate(self) -> ValidationResult:
        """Validate this AST node and return any issues found.

        Runs a suite of validators to check for:
        - Undefined variable references
        - Unused variables
        - Missing labels (performance issues)
        - Unreachable conditions
        - Type mismatches
        - And other common query anti-patterns

        Returns:
            ValidationResult containing all issues found

        Example:
            >>> result = query.cypher_validate()
            >>> if not result.is_valid:
            ...     print(result)

        """
        result = ValidationResult()

        # Run all validators
        _validate_undefined_variables(self, result)
        _validate_unused_variables(self, result)
        _validate_missing_labels(self, result)
        _validate_unreachable_conditions(self, result)
        _validate_return_all_with_limit(self, result)
        _validate_delete_without_detach(self, result)
        _validate_expensive_patterns(self, result)

        return result


class Algebraizable(ASTNode):
    """AST node that can be translated into a relational algebra operator.

    Subclasses (PatternPath, NodePattern, RelationshipPattern, PatternIntersection)
    implement a ``to_relation()`` method consumed by the STAR translator to build
    the query execution plan.
    """


# ============================================================================
# Query Structure
# ============================================================================


class Query(ASTNode):
    """Root node of a parsed Cypher query.

    Contains the ordered list of clauses that make up the query pipeline
    (e.g., MATCH → WHERE → WITH → RETURN). Clauses are executed sequentially,
    with each clause consuming and producing a binding table.
    """

    clauses: list[Clause] = Field(default_factory=list)


class UnionQuery(ASTNode):
    """Two or more queries joined by UNION [ALL].

    ``statements`` is the ordered list of component :class:`Query` objects.
    ``all_flags`` is a parallel list of booleans — ``all_flags[i]`` is
    ``True`` when the join between ``statements[i]`` and ``statements[i+1]``
    uses ``UNION ALL`` (no deduplication).
    """

    statements: list[Query] = Field(default_factory=list)
    all_flags: list[bool] = Field(default_factory=list)


class Clause(ASTNode, ABC):
    """Abstract base for Cypher query clauses.

    A clause is a top-level statement component (MATCH, RETURN, WITH, CREATE,
    etc.) that reads or modifies the binding table during query execution.
    """


class PatternIntersection(Algebraizable):
    """Intersection of multiple Patterns, implicit Join on shared variables."""

    pattern_list: list[Algebraizable]


# ============================================================================
# Reading Clauses
# ============================================================================


class Match(Clause):
    """MATCH clause — binds graph patterns to the binding table.

    Searches the graph for subgraphs matching *pattern* and adds one row per
    match. When *optional* is True (OPTIONAL MATCH), rows with no match are
    retained with NULL-filled columns. An optional *where* expression filters
    matches before they enter the binding table.
    """

    optional: bool = False
    pattern: Pattern | None = None
    where: Expression | None = None


class Unwind(Clause):
    """UNWIND clause — explodes a list into one row per element.

    Evaluates *expression* (which must yield a list) and produces one output
    row per element, binding each element to *alias*.
    """

    expression: Expression | None = None
    alias: str | None = None


class Call(Clause):
    """CALL clause — invokes a registered procedure.

    Calls the procedure identified by *procedure_name* with *arguments*,
    and optionally binds selected output columns via *yield_items*.
    A *where* filter may further restrict the yielded rows.
    """

    procedure_name: str | None = None
    arguments: list[Expression] = Field(default_factory=list)
    yield_items: list[YieldItem] = Field(default_factory=list)
    where: Expression | None = None


class YieldItem(ASTNode):
    """YIELD item in CALL clause."""

    variable: Variable | None = None
    alias: str | None = None


# ============================================================================
# Projection Clauses
# ============================================================================


class Return(Clause):
    """RETURN clause — specifies the query output.

    Projects expressions from the binding table into the result set, analogous
    to SQL SELECT. Supports DISTINCT deduplication, ORDER BY sorting, and
    SKIP/LIMIT pagination.
    """

    distinct: bool = False
    items: list[ReturnItem] = Field(default_factory=list)
    order_by: list[OrderByItem] | None = None
    #: Integer literal or an :class:`Expression` AST node (e.g. ``Parameter``).
    skip: Any | None = None
    #: Integer literal or an :class:`Expression` AST node (e.g. ``Parameter``).
    limit: Any | None = None


class With(Clause):
    """WITH clause — intermediate projection and scope boundary.

    Acts as a pipeline stage between clauses, projecting selected expressions
    into the downstream binding table. Supports the same modifiers as RETURN
    (DISTINCT, ORDER BY, SKIP, LIMIT) plus an optional WHERE filter. Variables
    not projected by WITH are not visible to subsequent clauses.
    """

    distinct: bool = False
    items: list[ReturnItem] = Field(default_factory=list)
    where: Expression | None = None
    order_by: list[OrderByItem] | None = None
    #: Integer literal or an :class:`Expression` AST node (e.g. ``Parameter``).
    skip: Any | None = None
    #: Integer literal or an :class:`Expression` AST node (e.g. ``Parameter``).
    limit: Any | None = None


class ReturnItem(ASTNode):
    """Item in RETURN or WITH clause."""

    expression: Expression | None = None
    alias: str | None = None


class OrderByItem(ASTNode):
    """ORDER BY item.

    ``nulls_placement`` controls where null values appear in the sorted output:
    ``"first"`` puts nulls before non-nulls; ``"last"`` (or ``None``) puts them
    after — matching Neo4j's default NULLS LAST behaviour.
    """

    expression: Expression | None = None
    ascending: bool = True
    nulls_placement: str | None = None  # "first", "last", or None (= last)


class ReturnAll(ASTNode):
    r"""RETURN \* or WITH \*."""


# ============================================================================
# Writing Clauses
# ============================================================================


class Create(Clause):
    """CREATE clause — inserts new nodes and relationships into the graph.

    Creates the entities described by *pattern*. If a variable in the pattern
    is already bound, the existing entity is reused; otherwise a new entity is
    created with any specified labels and properties.
    """

    pattern: Pattern | None = None


class Merge(Clause):
    """MERGE clause — creates a pattern only if it does not already exist.

    Performs an upsert: if *pattern* matches existing data, the match is bound;
    otherwise the pattern is created. Optional *on_create* and *on_match* SET
    actions run conditionally depending on whether a new entity was created.
    """

    pattern: Pattern | None = None
    on_create: list[SetItem] | None = None
    on_match: list[SetItem] | None = None


class Delete(Clause):
    """DELETE clause — removes nodes or relationships from the graph.

    Deletes the entities referenced by *expressions*. When *detach* is True
    (DETACH DELETE), any relationships connected to deleted nodes are
    automatically removed first.
    """

    detach: bool = False
    expressions: list[Expression] = Field(default_factory=list)


class Set(Clause):
    """SET clause — modifies properties or labels on existing entities.

    Contains a list of :class:`SetItem` subclasses that specify individual
    property assignments, label additions, or bulk property replacements.
    All mutations within a single SET are applied atomically per row.
    """

    items: list[SetItem] = Field(default_factory=list)


class SetItem(ASTNode):
    """Base class for items in SET clause."""

    variable: Variable | None = None
    property: str | None = None
    expression: Expression | None = None
    labels: list[str] = Field(default_factory=list)


class SetPropertyItem(SetItem):
    """SET n.property = value item."""

    variable: Variable
    property: str
    value: Expression


class SetLabelsItem(SetItem):
    """SET n:Label item."""

    variable: Variable
    labels: list[str]


class SetAllPropertiesItem(SetItem):
    """SET n = {map} item."""

    variable: Variable
    properties: Expression


class AddAllPropertiesItem(SetItem):
    """SET n += {map} item."""

    variable: Variable
    properties: Expression


class Remove(Clause):
    """REMOVE clause — removes properties or labels from existing entities.

    Contains a list of :class:`RemoveItem` entries specifying which properties
    or labels to strip from the referenced variables.
    """

    items: list[RemoveItem] = Field(default_factory=list)


class RemoveItem(ASTNode):
    """Item in REMOVE clause."""

    variable: Variable | None = None
    property: str | None = None
    labels: list[str] = Field(default_factory=list)


class Foreach(Clause):
    """FOREACH clause — iterative list mutation.

    Iterates over every element of *list_expression*, binds it to *variable*,
    and executes the inner *clauses* (SET, CREATE, MERGE, DELETE, REMOVE) for
    each element.  This is a side-effect-only construct; *variable* does not
    escape into the outer query scope.
    """

    variable: str | None = None
    list_expression: Expression | None = None
    clauses: list[Clause] = Field(default_factory=list)


# ============================================================================
# Patterns
# ============================================================================


class Pattern(ASTNode):
    """Pattern containing path components."""

    paths: list[PatternPath] = Field(default_factory=list)


class PatternPath(Algebraizable):
    """A single path in a pattern.

    Represents a complete path pattern that may have an optional binding variable.
    For example: p = (a)-[r]->(b)

    Attributes:
        variable: Variable instance for path binding (e.g., Variable(name="p")), optional
        elements: List of NodePattern and RelationshipPattern elements forming the path

    Example:
        >>> path = PatternPath(
        ...     variable=Variable(name="path"),
        ...     elements=[
        ...         NodePattern(variable=Variable(name="a")),
        ...         RelationshipPattern(variable=Variable(name="r")),
        ...         NodePattern(variable=Variable(name="b"))
        ...     ]
        ... )

    """

    variable: Variable | None = None
    elements: list[NodePattern | RelationshipPattern] = Field(
        default_factory=list,
    )
    #: ``"none"`` for normal paths, ``"one"`` for ``shortestPath``,
    #: ``"all"`` for ``allShortestPaths``.
    shortest_path_mode: str = "none"


class NodePattern(Algebraizable):
    """Node pattern in MATCH/CREATE clauses.

    Represents a node pattern like (n:Person {name: 'Alice'}) in Cypher queries.

    Attributes:
        variable: Variable instance representing the node's binding name (e.g., Variable(name="n"))
        labels: List of label names applied to this node
        properties: Property map as dict (optional)

    Example:
        >>> node = NodePattern(
        ...     variable=Variable(name="person"),
        ...     labels=["Person"],
        ...     properties={"name": "Alice"}
        ... )
        >>> print(node.variable.name)  # "person"

    """

    variable: Variable | None = None
    labels: list[str] = Field(default_factory=list)
    properties: dict[str, Any] = {}


class RelationshipPattern(Algebraizable):
    """Relationship pattern in MATCH/CREATE clauses.

    Represents a relationship pattern like -[r:KNOWS]-> in Cypher queries.

    Attributes:
        variable: Optional Variable instance representing the relationship's binding name (e.g., Variable(name="r"))
        labels: List of relationship type names
        properties: Property map as dict (optional)
        direction: Relationship direction token from RelationshipDirection ("<-", "->", or "-")
        length: PathLength specification for variable-length relationships (optional)
        where: WHERE condition for relationship patterns (optional)

    Example:
        >>> rel = RelationshipPattern(
        ...     variable=Variable(name="knows"),
        ...     labels=["KNOWS"],
        ...     direction=RelationshipDirection.RIGHT
        ... )
        >>> print(rel.variable.name)  # "knows"

    """

    variable: Variable | None = None
    labels: list[str] = Field(default_factory=list)
    properties: dict[str, Any] | None = None
    direction: RelationshipDirection
    length: PathLength | None = None
    where: Expression | None = None


class PathLength(ASTNode):
    """Variable-length path specification."""

    min: int | None = None
    max: int | None = None
    unbounded: bool = False


# ============================================================================
# Expressions
# ============================================================================


class Expression(ASTNode, ABC):
    """Abstract base for all Cypher expression nodes.

    Expressions produce values when evaluated against a binding table row.
    Subclasses cover literals, variables, operators, property access, function
    calls, and advanced constructs (comprehensions, quantifiers, CASE, REDUCE).
    """


class BinaryExpression(Expression, ABC):
    """Abstract base for expressions with a left operand, operator, and right operand.

    Logical operators (Or, And, Xor) additionally use an *operands* list to
    represent chains of the same operator without deep nesting.
    """

    operator: str
    left: Expression | None = None
    right: Expression | None = None


class Or(BinaryExpression):
    """Logical OR — true when any operand is true (Kleene three-valued logic)."""

    operands: list[Expression] = Field(default_factory=list)
    operator: str = "OR"


class Xor(BinaryExpression):
    """Logical XOR — true when exactly one operand is true (Kleene three-valued logic)."""

    operands: list[Expression] = Field(default_factory=list)
    operator: str = "XOR"


class And(BinaryExpression):
    """Logical AND — true when all operands are true (Kleene three-valued logic)."""

    operands: list[Expression] = Field(default_factory=list)
    operator: str = "AND"


class Not(Expression):
    """Logical NOT — negates its operand (Kleene three-valued logic: NOT NULL = NULL)."""

    operand: Expression | None = None


class Comparison(BinaryExpression):
    """Comparison expression (=, <>, <, >, <=, >=)."""


class StringPredicate(BinaryExpression):
    """String predicate (STARTS WITH, ENDS WITH, CONTAINS, =~, IN)."""


class NullCheck(Expression):
    """IS NULL or IS NOT NULL check."""

    operator: str  # "IS NULL" or "IS NOT NULL"
    operand: Expression | None = None


class LabelPredicate(Expression):
    """Label predicate check: ``n:Person`` or ``n:Person:Employee``.

    Returns ``True`` when the node bound to *operand* has all the specified
    labels, ``False`` otherwise.  In the current single-label entity model,
    ``n:A:B`` (two different labels) always returns ``False``.

    Attributes:
        operand: The expression being tested (typically a ``Variable``).
        labels: One or more label names that must all match.

    """

    operand: Expression | None = None
    labels: list[str] = []


class Arithmetic(BinaryExpression):
    r"""Arithmetic expression (+, -, \*, /, %, ^)."""


class Unary(Expression):
    """Unary expression (+, -)."""

    operator: str
    operand: Expression | None = None


# ============================================================================
# Property Access and Indexing
# ============================================================================


class PropertyLookup(Expression):
    """Property access (e.g., n.name).

    .. deprecated::
        The ``variable`` field is deprecated. Use ``expression`` instead.
    """

    expression: Expression | None = None
    property: str | None = None
    # Legacy field for backward compatibility - deprecated, use expression instead
    variable: Variable | None = None

    def model_post_init(self, __context: Any) -> None:
        """Emit deprecation warning when legacy ``variable`` field is used."""
        super().model_post_init(__context)
        if self.variable is not None:
            from shared.deprecation import emit_deprecation

            emit_deprecation(
                "PropertyLookup.variable",
                since="0.0.19",
                removed_in="0.1.0",
                alternative="PropertyLookup.expression",
            )


class IndexLookup(Expression):
    """Array/string indexing (e.g., list[0])."""

    expression: Expression | None = None
    index: Expression | None = None


class Slicing(Expression):
    """Array/string slicing (e.g., list[1..3])."""

    expression: Expression | None = None
    start: Expression | None = None
    end: Expression | None = None


# ============================================================================
# Literals
# ============================================================================


class Literal(Expression, ABC):
    """Base class for literal values."""

    value: Any

    def evaluate(self) -> Any:
        """Evaluate the literal to its value."""
        return self.value


class IntegerLiteral(Literal):
    """Integer literal."""

    value: int


class FloatLiteral(Literal):
    """Float literal."""

    value: float


class StringLiteral(Literal):
    """String literal."""

    value: str


class BooleanLiteral(Literal):
    """Boolean literal."""

    value: bool


class NullLiteral(Literal):
    """NULL literal."""

    value: None = None


class ListLiteral(Literal):
    """List literal."""

    value: list[Any] = Field(default_factory=list)
    elements: list[Expression] = Field(default_factory=list)


class MapLiteral(Literal):
    """Map literal."""

    value: dict[str, Any] = Field(default_factory=dict)
    entries: dict[str, Expression] = Field(default_factory=dict)


# ============================================================================
# Variables and Parameters
# ============================================================================


class Variable(Expression):
    """Variable reference in Cypher queries.

    Represents a variable name used in expressions, patterns, and bindings.
    Variables are used throughout the AST to reference nodes, relationships,
    paths, and other values.

    Attributes:
        name: The variable name (e.g., 'n', 'person', 'rel')

    Note:
        As of the latest refactoring, all variable references in the AST
        (including in patterns, comprehensions, and other binding contexts)
        are represented as Variable instances, not plain strings. This ensures
        consistency throughout the AST structure.

    Examples:
        >>> # In patterns
        >>> node = NodePattern(variable=Variable(name="n"), labels=["Person"])
        >>>
        >>> # In expressions
        >>> return_item = ReturnItem(expression=Variable(name="n"))
        >>>
        >>> # In comprehensions
        >>> comp = ListComprehension(variable=Variable(name="x"), ...)

    """

    name: str

    def __hash__(self) -> int:
        """Hash based on variable name."""
        return hash("__VARIABLE__" + self.name)


class Parameter(Expression):
    """Query parameter ($param)."""

    name: str


# ============================================================================
# Functions
# ============================================================================


class FunctionInvocation(Expression):
    """Scalar or aggregation function call (e.g., ``toUpper(n.name)``, ``count(*)``).

    The *name* field may be a plain string or a namespace dict for qualified
    calls like ``date.truncate``. Use the :attr:`function_name` property to
    get the normalised string form for registry lookup.
    """

    name: str | dict[str, str]  # Simple name or {namespace, name}
    arguments: dict[str, Any] | list[ASTNode | None] | None = None
    distinct: bool = False

    @property
    def function_name(self) -> str:
        """Return the normalised function name as a plain string.

        ``name`` may be either a bare string (e.g. ``"toUpper"``) or a
        namespace dict produced by the grammar for qualified calls such as
        ``date.truncate`` (represented as ``{"namespace": "date",
        "name": "truncate"}``).  This property returns the qualified name
        ``"date.truncate"`` so the scalar-function registry can look it up
        directly.
        """
        if isinstance(self.name, dict):
            namespace = self.name.get("namespace", "")
            bare = self.name.get("name", "")
            return f"{namespace}.{bare}" if namespace else bare
        return self.name


class CountStar(Expression):
    """COUNT(*) function."""


# ============================================================================
# Advanced Expressions
# ============================================================================


class Exists(Expression):
    """EXISTS subquery — tests whether a pattern or subquery produces any rows.

    Returns ``True`` if *content* (a :class:`Pattern` or :class:`Query`)
    matches at least one result, ``False`` otherwise. Evaluated using batch
    semantics in the binding evaluator.
    """

    content: Pattern | Query | None = None


class ListComprehension(Expression):
    """List comprehension expression: [x IN list WHERE pred | expr].

    Represents Cypher list comprehension syntax for transforming lists.

    Attributes:
        variable: Variable instance for the iteration variable (e.g., Variable(name="x"))
        list_expr: Expression that evaluates to a list
        where: Optional filter predicate
        map_expr: Optional transformation expression

    Example:
        >>> # [x IN [1,2,3] WHERE x > 1 | x * 2]
        >>> comp = ListComprehension(
        ...     variable=Variable(name="x"),
        ...     list_expr=ListLiteral(value=[1,2,3]),
        ...     where=Comparison(operator=">", left=Variable(name="x"), right=IntegerLiteral(value=1)),
        ...     map_expr=Arithmetic(operator="*", left=Variable(name="x"), right=IntegerLiteral(value=2))
        ... )

    """

    variable: Variable | None = None
    list_expr: Expression | None = None
    where: Expression | None = None
    map_expr: Expression | None = None


class PatternComprehension(Expression):
    """Pattern comprehension expression: [path = pattern WHERE pred | expr].

    Represents Cypher pattern comprehension for matching and transforming graph patterns.

    Attributes:
        variable: Variable instance for the path binding (e.g., Variable(name="path"))
        pattern: Graph pattern to match
        where: Optional filter predicate
        map_expr: Optional transformation expression

    Example:
        >>> # [p = (a)-[:KNOWS]->(b) WHERE b.age > 30 | b.name]
        >>> comp = PatternComprehension(
        ...     variable=Variable(name="p"),
        ...     pattern=Pattern(...),
        ...     where=Comparison(...),
        ...     map_expr=PropertyLookup(...)
        ... )

    """

    variable: Variable | None = None
    pattern: Pattern | None = None
    where: Expression | None = None
    map_expr: Expression | None = None


class MapProjection(Expression):
    """Map projection expression: node{.prop, computed: expr}.

    Projects a map/object with selected or computed properties.

    Attributes:
        variable: Variable instance for the source object (e.g., Variable(name="node"))
        elements: List of MapElement items defining projections
        include_all: Whether to include all properties (.* syntax)

    Example:
        >>> # person{.name, .age, adult: person.age >= 18}
        >>> proj = MapProjection(
        ...     variable=Variable(name="person"),
        ...     elements=[
        ...         MapElement(property="name"),
        ...         MapElement(property="age"),
        ...         MapElement(property="adult", expression=Comparison(...))
        ...     ]
        ... )

    """

    variable: Variable | None = None
    elements: list[MapElement] = Field(default_factory=list)
    include_all: bool = False


class MapElement(ASTNode):
    """Element in map projection."""

    property: str | None = None
    expression: Expression | None = None
    all_properties: bool = False


class CaseExpression(Expression):
    """CASE expression — conditional value selection.

    When *expression* is set (simple form), each WHEN condition is compared to it
    for equality. When *expression* is None (searched form), each WHEN condition
    is evaluated as a boolean. The first matching WHEN returns its result;
    *else_expr* provides a fallback (NULL if absent).
    """

    expression: Expression | None = None  # For simple CASE
    when_clauses: list[WhenClause] = Field(default_factory=list)
    else_expr: Expression | None = None


class WhenClause(ASTNode):
    """WHEN clause in CASE expression."""

    condition: Expression | None = None
    result: Expression | None = None


class Reduce(Expression):
    """REDUCE expression for list aggregation.

    Iterates over a list, accumulating values using a custom expression.

    Attributes:
        accumulator: Variable instance for the accumulator (e.g., Variable(name="sum"))
        initial: Initial value expression for the accumulator
        variable: Variable instance for the iteration variable (e.g., Variable(name="x"))
        list_expr: Expression that evaluates to a list
        map_expr: Expression to compute new accumulator value

    Example:
        >>> # REDUCE(sum = 0, x IN [1,2,3] | sum + x)
        >>> reduce_expr = Reduce(
        ...     accumulator=Variable(name="sum"),
        ...     initial=IntegerLiteral(value=0),
        ...     variable=Variable(name="x"),
        ...     list_expr=ListLiteral(value=[1,2,3]),
        ...     map_expr=Arithmetic(operator="+", left=Variable(name="sum"), right=Variable(name="x"))
        ... )

    """

    accumulator: Variable | None = None
    initial: Expression | None = None
    variable: Variable | None = None
    list_expr: Expression | None = None
    map_expr: Expression | None = None


class Quantifier(Expression):
    """Quantifier expression: ALL, ANY, NONE, SINGLE.

    Tests whether a predicate holds for elements in a list.

    Attributes:
        quantifier: Type of quantifier ("ALL", "ANY", "NONE", "SINGLE")
        variable: Variable instance for the iteration variable (e.g., Variable(name="x"))
        list_expr: Expression that evaluates to a list
        where: Predicate expression to test

    Examples:
        >>> # ALL(x IN [1,2,3] WHERE x > 0)
        >>> all_expr = Quantifier(
        ...     quantifier="ALL",
        ...     variable=Variable(name="x"),
        ...     list_expr=ListLiteral(value=[1,2,3]),
        ...     where=Comparison(operator=">", left=Variable(name="x"), right=IntegerLiteral(value=0))
        ... )
        >>>
        >>> # ANY(x IN list WHERE x = value)
        >>> any_expr = Quantifier(
        ...     quantifier="ANY",
        ...     variable=Variable(name="x"),
        ...     list_expr=Variable(name="list"),
        ...     where=Comparison(operator="=", left=Variable(name="x"), right=Variable(name="value"))
        ... )

    """

    quantifier: str  # "ALL", "ANY", "NONE", "SINGLE"
    variable: Variable | None = None
    list_expr: Expression | None = None
    where: Expression | None = None


# ============================================================================
# Special Functions
# ============================================================================


class ShortestPath(Expression):
    """SHORTESTPATH function."""

    pattern: Pattern | None = None


class AllShortestPaths(Expression):
    """ALLSHORTESTPATHS function."""

    pattern: Pattern | None = None


# ============================================================================
# AST Converter — extracted to pycypher.ast_converter
# Re-exported here for backward compatibility via __getattr__ lazy loading.
# This avoids a circular import: ast_converter imports ast_models at the
# module level, so ast_models must not import ast_converter eagerly.
# ============================================================================

_CONVERTER_REEXPORTS: dict[str, str] = {
    "ASTConverter": "ASTConverter",
    "_friendly_parse_error": "_friendly_parse_error",
    "_parse_cypher_cached": "_parse_cypher_cached",
}


def __getattr__(name: str) -> Any:
    if name in _CONVERTER_REEXPORTS:
        import pycypher.ast_converter as _conv

        return getattr(_conv, _CONVERTER_REEXPORTS[name])
    msg = f"module {__name__!r} has no attribute {name!r}"
    raise AttributeError(msg)


# (end of converter re-exports)
# ============================================================================
# Validation Implementation
# ============================================================================


def _collect_defined_variables(node: ASTNode) -> Set[str]:
    """Collect all variables defined in patterns and other binding contexts."""
    defined = set()

    # Variables from MATCH patterns
    for match in node.find_all(Match):
        if cast("Match", match).pattern:
            for path in getattr(cast("Match", match).pattern, "paths", []):
                # Node variables
                for elem in path.elements:
                    if (isinstance(elem, NodePattern) and elem.variable) or (
                        isinstance(elem, RelationshipPattern) and elem.variable
                    ):
                        defined.add(elem.variable.name)
                # Path variable
                if path.variable:
                    defined.add(path.variable.name)

    # Variables from CREATE patterns
    for create in node.find_all(Create):
        if cast("Create", create).pattern:
            for path in getattr(cast("Create", create).pattern, "paths", []):
                for elem in path.elements:
                    if (isinstance(elem, NodePattern) and elem.variable) or (
                        isinstance(elem, RelationshipPattern) and elem.variable
                    ):
                        defined.add(elem.variable.name)

    # Variables from UNWIND
    for unwind in node.find_all(Unwind):
        if cast("Unwind", unwind).alias:
            defined.add(cast("Unwind", unwind).alias)

    # Variables from WITH (creates new scope)
    for with_clause in node.find_all(With):
        for item in cast("With", with_clause).items:
            if item.alias:
                defined.add(item.alias)
            elif isinstance(item.expression, Variable):
                defined.add(item.expression.name)

    return defined


def _collect_definition_ids(node: ASTNode) -> Set[int]:
    """Collect IDs of Variable nodes that act as definitions."""
    ids = set()
    for match in node.find_all(Match):
        if cast("Match", match).pattern:
            for path in getattr(cast("Match", match).pattern, "paths", []):
                for elem in path.elements:
                    if (isinstance(elem, NodePattern) and elem.variable) or (
                        isinstance(elem, RelationshipPattern) and elem.variable
                    ):
                        ids.add(id(elem.variable))
                if path.variable:
                    ids.add(id(path.variable))
    for create in node.find_all(Create):
        if cast("Create", create).pattern:
            for path in getattr(cast("Create", create).pattern, "paths", []):
                for elem in path.elements:
                    if (isinstance(elem, NodePattern) and elem.variable) or (
                        isinstance(elem, RelationshipPattern) and elem.variable
                    ):
                        ids.add(id(elem.variable))
    return ids


def extract_referenced_variables(node: ASTNode) -> set[str]:
    """Extract all variable names referenced in an AST expression.

    Uses the AST's built-in ``find_all(Variable)`` visitor to collect variable
    names.  This traversal is complete (handles all AST node types) and
    depth-limited (raises :exc:`SecurityError` if nesting exceeds the
    configured maximum).

    For ``PropertyLookup`` nodes (e.g. ``p.name``), extracts the base variable
    name (``p``).

    This is the **canonical** variable extraction function — all call sites
    that need variable names from expression ASTs should use this function
    rather than implementing ad-hoc traversal.

    Args:
        node: An AST node (typically a WHERE predicate or expression).

    Returns:
        Set of variable name strings.

    """
    refs: set[str] = set()
    for var in node.find_all(Variable):
        refs.add(var.name)
    return refs


def _collect_referenced_variables(node: ASTNode) -> Set[str]:
    """Collect all variables referenced in expressions."""
    referenced = set()
    definition_ids = _collect_definition_ids(node)

    for var in node.find_all(Variable):
        if id(var) not in definition_ids:
            referenced.add(cast("Variable", var).name)

    # Also check property lookups with legacy variable field
    for prop in node.find_all(PropertyLookup):
        if cast("PropertyLookup", prop).variable:
            # PropertyLookup variable is typically a reference
            if id(cast("PropertyLookup", prop).variable) not in definition_ids:
                referenced.add(
                    getattr(
                        cast("PropertyLookup", prop).variable,
                        "name",
                        None,
                    ),
                )

    return referenced


def _validate_undefined_variables(
    node: ASTNode,
    result: ValidationResult,
) -> None:
    """Check for references to undefined variables."""
    if not isinstance(node, Query):
        return

    defined = _collect_defined_variables(node)
    referenced = _collect_referenced_variables(node)

    undefined = referenced - defined
    for var in sorted(undefined):
        result.add_issue(
            ValidationSeverity.ERROR,
            f"Variable '{var}' is used but never defined",
            suggestion=f"Add '{var}' to a MATCH or CREATE pattern, or define it with UNWIND/WITH",
            code="UNDEFINED_VAR",
        )


def _validate_unused_variables(
    node: ASTNode,
    result: ValidationResult,
) -> None:
    """Check for variables that are defined but never used."""
    if not isinstance(node, Query):
        return

    defined = _collect_defined_variables(node)
    referenced = _collect_referenced_variables(node)

    # Also check what's returned
    returned = set()
    for ret in node.find_all(Return):
        for item in cast("Return", ret).items:
            if isinstance(item.expression, Variable):
                returned.add(item.expression.name)

    used = referenced | returned
    unused = defined - used

    for var in sorted(unused):
        result.add_issue(
            ValidationSeverity.WARNING,
            f"Variable '{var}' is defined but never used",
            suggestion=f"Remove '{var}' from the pattern or use it in WHERE/RETURN",
            code="UNUSED_VAR",
        )


def _validate_missing_labels(node: ASTNode, result: ValidationResult) -> None:
    """Check for MATCH patterns without labels (potential performance issue)."""
    for match in node.find_all(Match):
        if not cast("Match", match).pattern:
            continue

        for path in getattr(cast("Match", match).pattern, "paths", []):
            for elem in path.elements:
                if isinstance(elem, NodePattern):
                    if not elem.labels and not elem.properties:
                        var_name = (
                            elem.variable.name
                            if elem.variable
                            else "(anonymous)"
                        )
                        result.add_issue(
                            ValidationSeverity.WARNING,
                            f"Node pattern '{var_name}' has no labels or properties",
                            node_type="Match",
                            suggestion="Add a label to improve query performance via index usage",
                            code="MISSING_LABEL",
                        )


def _validate_unreachable_conditions(
    node: ASTNode,
    result: ValidationResult,
) -> None:
    """Check for unreachable WHERE conditions (like WHERE false)."""
    for match in node.find_all(Match):
        if cast("Match", match).where:
            if isinstance(
                cast("Match", match).where,
                BooleanLiteral,
            ) and not getattr(cast("Match", match).where, "value", None):
                result.add_issue(
                    ValidationSeverity.WARNING,
                    "WHERE clause is always false - this query will never return results",
                    node_type="Match",
                    suggestion="Remove the WHERE false condition or fix the logic",
                    code="UNREACHABLE_MATCH",
                )

            # Check for contradictory literal comparisons
            _check_contradictory_comparisons(
                cast("Match", match).where,
                result,
            )


def _check_contradictory_comparisons(
    expr: Any,
    result: ValidationResult,
) -> None:
    """Recursively check for contradictory comparisons with literals."""
    # Check for Comparison class (not ComparisonExpression)
    if expr.__class__.__name__ == "Comparison":
        # Check if both sides are literals
        left_is_literal = expr.left.__class__.__name__ in (
            "IntegerLiteral",
            "FloatLiteral",
            "StringLiteral",
            "BooleanLiteral",
        )
        right_is_literal = expr.right.__class__.__name__ in (
            "IntegerLiteral",
            "FloatLiteral",
            "StringLiteral",
            "BooleanLiteral",
        )

        if left_is_literal and right_is_literal:
            left_val = expr.left.value
            right_val = expr.right.value
            op = expr.operator

            # Evaluate the comparison
            try:
                if op == ">":
                    always_false = not (left_val > right_val)
                elif op == "<":
                    always_false = not (left_val < right_val)
                elif op == ">=":
                    always_false = not (left_val >= right_val)
                elif op == "<=":
                    always_false = not (left_val <= right_val)
                elif op == "=":
                    always_false = left_val != right_val
                elif op == "<>":
                    always_false = left_val == right_val
                else:
                    always_false = False

                if always_false:
                    result.add_issue(
                        ValidationSeverity.ERROR,
                        f"Contradictory comparison: {left_val} {op} {right_val} is always false",
                        node_type="ComparisonExpression",
                        suggestion="Review the comparison logic",
                        code="CONTRADICTORY_COMPARISON",
                    )
            except (TypeError, ValueError):  # fmt: skip  # parens required for Python <3.14
                # Can't compare these types
                pass

    # Recursively check child expressions
    if hasattr(expr, "__dict__"):
        for attr_value in expr.__dict__.values():
            if isinstance(attr_value, list):
                for item in attr_value:
                    _check_contradictory_comparisons(item, result)
            elif hasattr(attr_value, "__dict__"):
                _check_contradictory_comparisons(attr_value, result)


def _validate_return_all_with_limit(
    node: ASTNode,
    result: ValidationResult,
) -> None:
    """Check for RETURN * with LIMIT (may return unexpected results)."""
    for ret in node.find_all(Return):
        ret_clause = cast("Return", ret)
        has_return_all = any(
            isinstance(item.expression, ReturnAll) for item in ret_clause.items
        )
        if has_return_all and cast("Return", ret).limit:
            result.add_issue(
                ValidationSeverity.INFO,
                "Using RETURN * with LIMIT may return arbitrary results",
                node_type="Return",
                suggestion="Consider adding ORDER BY to make results deterministic",
                code="NONDETERMINISTIC_LIMIT",
            )


def _validate_delete_without_detach(
    node: ASTNode,
    result: ValidationResult,
) -> None:
    """Check for DELETE of nodes that might have relationships."""
    for delete in node.find_all(Delete):
        if (
            not cast("Delete", delete).detach
            and cast("Delete", delete).expressions
        ):
            # Check if we're deleting node variables (not properties)
            for expr in cast("Delete", delete).expressions:
                if isinstance(expr, Variable):
                    result.add_issue(
                        ValidationSeverity.WARNING,
                        f"Deleting node '{expr.name}' without DETACH may fail if it has relationships",
                        node_type="Delete",
                        suggestion="Use DETACH DELETE to automatically remove relationships",
                        code="MISSING_DETACH",
                    )


def _validate_expensive_patterns(
    node: ASTNode,
    result: ValidationResult,
) -> None:
    """Check for potentially expensive query patterns."""
    # Check for multiple MATCH clauses without connecting variables
    matches = node.find_all(Match)
    if len(matches) >= 2:
        match_vars = []
        for match in matches:
            if cast("Match", match).pattern:
                vars_in_match = set()
                for path in getattr(cast("Match", match).pattern, "paths", []):
                    for elem in path.elements:
                        if (
                            isinstance(elem, NodePattern) and elem.variable
                        ) or (
                            isinstance(elem, RelationshipPattern)
                            and elem.variable
                        ):
                            vars_in_match.add(elem.variable.name)
                match_vars.append(vars_in_match)

        # Check if consecutive matches share variables
        for i in range(len(match_vars) - 1):
            if not match_vars[i] & match_vars[i + 1]:
                result.add_issue(
                    ValidationSeverity.WARNING,
                    "Multiple MATCH clauses with no shared variables may create a Cartesian product",
                    node_type="Match",
                    suggestion="Ensure MATCH patterns share variables or add WHERE conditions to connect them",
                    code="CARTESIAN_PRODUCT",
                )
                break  # Only report once

    # Check for variable-length paths without upper bound
    for rel in node.find_all(RelationshipPattern):
        if cast("RelationshipPattern", rel).length and getattr(
            cast("RelationshipPattern", rel).length,
            "unbounded",
            False,
        ):
            result.add_issue(
                ValidationSeverity.WARNING,
                "Unbounded variable-length relationship may cause performance issues",
                node_type="RelationshipPattern",
                suggestion="Add an upper bound to the relationship length (e.g., *1..10)",
                code="UNBOUNDED_RELATIONSHIP",
            )


# ============================================================================
# Utility Functions
# ============================================================================


def convert_ast(raw_ast: Any) -> ASTNode | None:
    """Convert a dictionary-based AST to typed Pydantic models.

    Args:
        raw_ast: Dictionary or other value from grammar parser

    Returns:
        Typed ASTNode or None

    Example:
        >>> from pycypher.grammar_parser import GrammarParser
        >>> parser = GrammarParser()
        >>> raw_ast = parser.parse_to_ast("MATCH (n) RETURN n")
        >>> typed_ast = convert_ast(raw_ast)
        >>> print(typed_ast.pretty())

    """
    from pycypher.ast_converter import ASTConverter as _ASTConverter

    converter = _ASTConverter()
    return converter.convert(raw_ast)


def traverse_ast(node: ASTNode) -> Iterator[ASTNode]:
    """Traverse an AST depth-first.

    Args:
        node: Root AST node

    Yields:
        Each node in the tree

    Example:
        >>> for ast_node in traverse_ast(typed_ast):
        ...     print(ast_node.__class__.__name__)

    """
    return node.traverse()


def find_nodes(node: ASTNode, node_type: type) -> list[ASTNode]:
    """Find all nodes of a specific type.

    Args:
        node: Root AST node
        node_type: Type to search for

    Returns:
        List of matching nodes

    Example:
        >>> matches = find_nodes(typed_ast, Match)
        >>> print(f"Found {len(matches)} MATCH clauses")

    """
    return node.find_all(node_type)


def print_ast(node: ASTNode, indent: int = 0) -> None:
    """Pretty print an AST.

    Args:
        node: AST node to print
        indent: Initial indentation level

    Example:
        >>> print_ast(typed_ast)

    """


# ============================================================================
# Validation Framework - More Cowbell! 🔔
# ============================================================================


def validate_ast(node: ASTNode, strict: bool = False) -> ValidationResult:
    """Validate an AST for common issues and anti-patterns.

    This function performs comprehensive validation including:
    - Undefined variable detection
    - Unreachable code detection
    - Performance anti-patterns
    - Type consistency checks

    Args:
        node: Root AST node to validate
        strict: If True, treat warnings as errors

    Returns:
        ValidationResult containing all issues found

    Example:
        >>> result = validate_ast(typed_ast)
        >>> if not result.is_valid:
        ...     print(result)
        ...     for error in result.errors:
        ...         print(f"Error: {error.message}")

    """
    result = ValidationResult()

    # Run all validators
    _validate_undefined_variables(node, result)
    _validate_unused_variables(node, result)
    _validate_missing_labels(node, result)
    _validate_unreachable_conditions(node, result)
    _validate_return_all_with_limit(node, result)
    _validate_delete_without_detach(node, result)
    _validate_expensive_patterns(node, result)

    # Convert warnings to errors in strict mode
    if strict:
        for issue in result.issues:
            if issue.severity == ValidationSeverity.WARNING:
                issue.severity: Literal[ValidationSeverity] = (
                    ValidationSeverity.ERROR
                )

    return result
