from __future__ import annotations

from enum import Enum
from typing import Any, Optional, cast

import pandas as pd
from pydantic import BaseModel, Field
from shared.logger import LOGGER
from typing_extensions import Annotated

from pycypher.ast_models import Algebraizable, Variable, random_hash

LOGGER.setLevel(level="DEBUG")
ID_COLUMN: str = "__ID__"
RELATIONSHIP_SOURCE_COLUMN: str = "__SOURCE__"
RELATIONSHIP_TARGET_COLUMN: str = "__TARGET__"


def flatten(lst: list[Any]) -> list[Any]:
    """Flatten a nested list."""
    flat_list: list[Any] = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(flatten(item))
        else:
            flat_list.append(item)
    return flat_list


EntityType = Annotated[str, ...]
Attribute = Annotated[str, ...]
RelationshipType = Annotated[str, ...]
ColumnName: Annotated[..., ...] = Annotated[str, ...]
VariableMap = Annotated[dict[Variable, ColumnName], ...]
VariableTypeMap = Annotated[dict[Variable, EntityType | RelationshipType], ...]
AttributeMap = Annotated[dict[Attribute, ColumnName], ...]

# Type aliases documenting variable_map semantics at different pipeline stages
# MatchVariableMap: Variable -> 32-hex-char hash column name (pre-WITH)
MatchVariableMap = dict  # Variable -> 32-hex-char hash column name (pre-WITH)
# AliasVariableMap: Variable -> alias string matching output column (post-WITH)
AliasVariableMap = (
    dict  # Variable -> alias string matching output column (post-WITH)
)


class ColumnFormat(Enum):
    """Describes the column naming convention used by a Relation's output.

    Attributes:
        PREFIXED_ENTITY: EntityTable/RelationshipTable output - columns are
            prefixed with the entity/relationship type, e.g. ``Person__name``,
            ``Person____ID__``, ``KNOWS____SOURCE__``.
        HASH_ID: FilterRows/Join/Projection/SelectColumns output - ID columns
            are 32-hex-char hash strings generated by ``random_hash()``.
        ALIAS: ExpressionProjection/Aggregation output - columns are plain
            alias strings matching user-supplied names in WITH/RETURN clauses.
        MIXED: Transitional format used when both hash IDs and entity-prefixed
            columns may coexist (e.g. PropertyModification).

    """

    PREFIXED_ENTITY = (
        "prefixed_entity"  # EntityTable: "Person__name", "Person____ID__"
    )
    HASH_ID = "hash_id"  # FilterRows/Join: 32-hex-char hash columns
    ALIAS = "alias"  # ExpressionProjection/Aggregation: plain alias strings
    MIXED = "mixed"  # PropertyModification: transitional mixed format


class BooleanCondition(BaseModel):
    pass


class Equals(BooleanCondition):
    """Equality condition between two expressions."""

    left: Any
    right: Any


class AttributeEqualsValue(Equals):
    """Condition that an attribute equals a specific value."""

    pass


class EntityMapping(BaseModel):
    """Mapping from entity types to the corresponding Table."""

    mapping: dict[EntityType, Any] = {}

    def __getitem__(self, key: EntityType) -> Any:
        return self.mapping[key]


class RelationshipMapping(BaseModel):
    """Mapping from relationship types to the corresponding Table."""

    mapping: dict[RelationshipType, Any] = {}

    def __getitem__(self, key: RelationshipType) -> Any:
        return self.mapping[key]


class Context(BaseModel):
    """Context for translation operations."""

    entity_mapping: EntityMapping = EntityMapping()
    relationship_mapping: RelationshipMapping = RelationshipMapping()


class Relation(BaseModel):
    """A `Relation` represents a tabular data structure with some metadata.

    Column Naming Convention
    ------------------------
    The ``column_format`` property describes how this relation names its
    output columns.  See ``ColumnFormat`` for the full taxonomy.

    The ``output_column_names()`` method returns the exact list of column
    names that ``to_pandas()`` will produce.  Downstream operators rely on
    this contract to build correct join keys and projections without
    materialising the DataFrame first.
    """

    source_algebraizable: Algebraizable | None = None
    variable_map: VariableMap = {}
    variable_type_map: VariableTypeMap = Field(
        default_factory=dict
    )  # e.g. "node" or "relationship"
    column_names: list[ColumnName] = []
    identifier: str = Field(default_factory=lambda: random_hash())

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        # Note: Pydantic models with default fields might have them set after init if passed as args
        # But we check self.column_names which should be set by super().__init__
        if not self.column_names:
            LOGGER.warning(
                msg=f"Relation {type(self).__name__} created without column_names specified."
            )

        self.column_names: list[ColumnName] = [
            str(column_name) for column_name in self.column_names
        ]

        self.variable_map: VariableMap = {
            var_name: str(column_name)
            for var_name, column_name in self.variable_map.items()
        }

        self.variable_type_map: VariableTypeMap = {
            var_name: var_type
            for var_name, var_type in self.variable_type_map.items()
        }

    @property
    def column_format(self) -> ColumnFormat:
        """Return the column naming format used by this relation's output.

        Subclasses must override this property to declare their naming
        convention.  The base implementation raises ``NotImplementedError``
        so that accidental use of an unimplemented subclass is caught early.
        """
        raise NotImplementedError(
            f"column_format not implemented for {type(self).__name__}"
        )

    def output_column_names(self) -> list[str]:
        """Return the list of column names produced by ``to_pandas()``.

        Subclasses must override this method.  The returned list must exactly
        match the column order and names of the DataFrame returned by
        ``to_pandas()``.

        Returns:
            list[str]: Column names in the order they appear in the output.

        """
        raise NotImplementedError(
            f"output_column_names not implemented for {type(self).__name__}"
        )

    def to_pandas(self, context: Context) -> pd.DataFrame:
        """Convert the Relation to a pandas DataFrame."""
        raise NotImplementedError(
            "to_pandas not implemented for base Relation class."
        )


class RelationIntersection(Relation):
    """Intersection of multiple Relations, implicit Join on shared variables."""

    relation_list: list[Relation]

    @property
    def column_format(self) -> ColumnFormat:
        """RelationIntersection produces hash-ID columns (same as Join)."""
        return ColumnFormat.HASH_ID

    def output_column_names(self) -> list[str]:
        """Return the ID column names tracked by this intersection."""
        return list(self.column_names)

    def variables_in_common(self):
        """Find variables in common across all relations in the intersection."""
        if not self.relation_list:
            return set()
        variables_in_common: set[Variable] = set(
            self.relation_list[0].variable_map.keys()
        )
        for relation in self.relation_list[1:]:
            variables_in_common.intersection_update(
                relation.variable_map.keys()
            )
        return variables_in_common


class EntityTable(Relation):
    """Source of truth for all IDs and attributes for a specific entity type."""

    entity_type: EntityType
    source_obj: Any = Field(default=None, repr=False)
    attribute_map: dict[Attribute, ColumnName] = Field(default_factory=dict)
    source_obj_attribute_map: dict[Attribute, str] = Field(
        default_factory=dict
    )  # Assume all table objects (e.g. DataFrames) have string column names.

    @property
    def column_format(self) -> ColumnFormat:
        """EntityTable produces entity-type-prefixed columns."""
        return ColumnFormat.PREFIXED_ENTITY

    def output_column_names(self) -> list[str]:
        """Return all prefixed column names: ID column plus attribute columns."""
        id_col = f"{self.entity_type}__{ID_COLUMN}"
        attr_cols = [
            f"{self.entity_type}__{col}" for col in self.attribute_map.values()
        ]
        return [id_col] + attr_cols

    def to_pandas(self, context: Context) -> pd.DataFrame:
        df: pd.DataFrame = self.source_obj
        # Disambiguate columns by prefixing with entity type
        rename_map = {col: f"{self.entity_type}__{col}" for col in df.columns}
        return df.rename(columns=rename_map)


class RelationshipTable(Relation):
    """Source of truth for all IDs and attributes for a specific relationship type."""

    relationship_type: RelationshipType
    source_obj: Any = Field(default=None, repr=False)
    attribute_map: dict[Attribute, ColumnName] = Field(default_factory=dict)
    source_obj_attribute_map: dict[Attribute, str] = Field(
        default_factory=dict
    )  # Assume all table objects (e.g. DataFrames) have string column names.

    @property
    def column_format(self) -> ColumnFormat:
        """RelationshipTable produces relationship-type-prefixed columns."""
        return ColumnFormat.PREFIXED_ENTITY

    def output_column_names(self) -> list[str]:
        """Return all prefixed column names: ID, SOURCE, TARGET, plus attributes."""
        prefix = self.relationship_type
        id_col = f"{prefix}__{ID_COLUMN}"
        src_col = f"{prefix}__{RELATIONSHIP_SOURCE_COLUMN}"
        tgt_col = f"{prefix}__{RELATIONSHIP_TARGET_COLUMN}"
        attr_cols = [
            f"{prefix}__{col}"
            for col in self.attribute_map.values()
            if col
            not in (
                ID_COLUMN,
                RELATIONSHIP_SOURCE_COLUMN,
                RELATIONSHIP_TARGET_COLUMN,
            )
        ]
        return [id_col, src_col, tgt_col] + attr_cols

    def to_pandas(self, context: Context) -> pd.DataFrame:
        """Convert the RelationshipTable to a pandas DataFrame."""
        df: pd.DataFrame = self.source_obj
        # Disambiguate columns by prefixing with relationship type
        rename_map = {
            col: f"{self.relationship_type}__{col}" for col in df.columns
        }
        return df.rename(columns=rename_map)


class ProjectionBase(Relation):
    """Abstract base class for all projection operators.

    Two concrete subclasses exist in this pipeline:

    * ``Projection`` — renames entity-prefixed columns to hash-ID column
      names, used during MATCH pattern translation.
    * ``ExpressionProjection`` (future) — evaluates arbitrary expressions
      and emits alias-named columns, used for WITH/RETURN clauses.

    Subclasses must implement ``project()`` to apply their specific
    column-selection or column-computation logic to an input DataFrame.
    """

    def project(self, df: pd.DataFrame) -> pd.DataFrame:
        """Apply the projection to a DataFrame and return the projected result.

        Args:
            df: Input DataFrame to project.

        Returns:
            pd.DataFrame: Projected DataFrame with the appropriate columns.

        Raises:
            NotImplementedError: If the subclass has not implemented this method.

        """
        raise NotImplementedError(
            f"project() not implemented for {type(self).__name__}"
        )


class Projection(ProjectionBase):
    """Selection of specific columns from a Relation.

    To be used in `RETURN` and `WITH` clauses.

    Renames entity-prefixed columns to hash-ID column names so that
    downstream operators work with stable, type-agnostic identifiers.
    """

    relation: Relation
    projected_column_names: dict[ColumnName, ColumnName]

    @property
    def column_format(self) -> ColumnFormat:
        """Projection renames entity columns to hash IDs."""
        return ColumnFormat.HASH_ID

    def output_column_names(self) -> list[str]:
        """Return the projected (target) column names."""
        return list(self.projected_column_names.values())

    def project(self, df: pd.DataFrame) -> pd.DataFrame:
        """Apply the column rename and selection to the given DataFrame.

        Args:
            df: Input DataFrame, typically from an ``EntityTable`` or
                ``RelationshipTable`` with entity-prefixed columns.

        Returns:
            pd.DataFrame: DataFrame containing only the projected columns,
                renamed according to ``projected_column_names``.

        """
        return df.rename(columns=self.projected_column_names)[
            list(self.projected_column_names.values())
        ]

    def to_pandas(self, context: Context) -> pd.DataFrame:
        """Convert the Projection to a pandas DataFrame."""
        base_df: pd.DataFrame = self.relation.to_pandas(context=context)
        return self.project(base_df)


class JoinType(Enum):
    """Enumeration of join types."""

    INNER = "INNER"
    LEFT = "LEFT"
    RIGHT = "RIGHT"
    FULL = "FULL"


class Join(Relation):
    """Join represents a join operation between two Relations."""

    join_type: JoinType = JoinType.INNER
    left: Relation
    right: Relation
    on_left: list[ColumnName]
    on_right: list[ColumnName]

    @property
    def column_format(self) -> ColumnFormat:
        """Join retains hash-ID columns from its inputs."""
        return ColumnFormat.HASH_ID

    def output_column_names(self) -> list[str]:
        """Return the ID column names kept after the join."""
        return list(self.column_names)

    def to_pandas(self, context: Context) -> pd.DataFrame:
        """Convert the Join to a pandas DataFrame.

        Only returns ID columns corresponding to variables, not attribute columns.
        """
        left_df: pd.DataFrame = self.left.to_pandas(context=context)
        right_df: pd.DataFrame = self.right.to_pandas(context=context)
        join_type_str: str = self.join_type.value.lower()
        joined_df: pd.DataFrame = pd.merge(
            left=left_df,
            right=right_df,
            how=join_type_str,
            left_on=self.on_left,
            right_on=self.on_right,
        )

        # Only keep columns that correspond to variables (ID columns)
        # Use column_names if specified, otherwise use variable_map values
        if self.column_names:
            columns_to_keep = [
                col for col in self.column_names if col in joined_df.columns
            ]
        else:
            columns_to_keep = [
                col
                for col in self.variable_map.values()
                if col in joined_df.columns
            ]

        return joined_df[columns_to_keep]


class SelectColumns(Relation):
    """Relation that projects a subset of columns from another relation."""

    relation: Relation
    column_names: list[ColumnName]

    @property
    def column_format(self) -> ColumnFormat:
        """SelectColumns passes through hash-ID columns unchanged."""
        return ColumnFormat.HASH_ID

    def output_column_names(self) -> list[str]:
        """Return the selected column names."""
        return list(self.column_names)

    def to_pandas(self, context: Context) -> pd.DataFrame:
        """Convert the SelectColumns into a pandas DataFrame."""
        df: pd.DataFrame = self.relation.to_pandas(context=context)
        # Select only the columns specified
        return df[[str(col) for col in self.column_names]]


class FilterRows(Relation):
    """Filter represents a filtering operation on a Relation.

    Produces only the ID columns from the upstream relation (semi-join
    semantics).  Attribute columns are fetched on-demand by downstream
    operators when needed.

    Currently supports ``AttributeEqualsValue`` conditions.  Additional
    condition types (e.g. ``ExpressionCondition``) will be added as the
    expression evaluator matures.
    """

    relation: Relation
    condition: BooleanCondition  # Placeholder for condition expression
    column_map: dict[ColumnName, ColumnName] = Field(default_factory=dict)

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)

    @property
    def column_format(self) -> ColumnFormat:
        """FilterRows returns hash-ID columns from the upstream relation."""
        return ColumnFormat.HASH_ID

    def output_column_names(self) -> list[str]:
        """Return the ID column names preserved after filtering."""
        return list(self.column_names)

    def to_pandas(self, context: Context) -> pd.DataFrame:
        """Convert the FilterRows relation to a pandas DataFrame.

        Only returns ID columns corresponding to variables, not attribute columns.
        Attributes are fetched on-demand via joins when needed.
        """
        base_df: pd.DataFrame = self.relation.to_pandas(context=context)

        match self.condition:
            case AttributeEqualsValue():
                # Filtering by attribute with specific value
                condition_attribute = self.condition.left
                condition_value: Any = (
                    self.condition.right.evaluate()
                    if hasattr(self.condition.right, "evaluate")
                    else self.condition.right
                )
                entity_type: EntityType = self.relation.variable_type_map[
                    next(iter(self.relation.variable_map.keys()))
                ]

                # Fetch entity table to access attribute for filtering
                entity_df: pd.DataFrame = context.entity_mapping[
                    entity_type
                ].to_pandas(context=context)

                # Get the attribute column name with entity type prefix
                attribute_column_name: ColumnName = context.entity_mapping[
                    entity_type
                ].attribute_map[condition_attribute]
                prefixed_attribute_column_name = (
                    f"{entity_type}__{attribute_column_name}"
                )

                # Filter entity table by attribute
                filtered_entity_df: pd.DataFrame = entity_df[
                    entity_df[prefixed_attribute_column_name]
                    == condition_value
                ]

                # Get the ID column name from base relation
                base_entity_id_column: ColumnName | None = None
                for var, col in self.relation.variable_map.items():
                    if self.relation.variable_type_map[var] == entity_type:
                        base_entity_id_column = col
                        break
                else:
                    raise ValueError(
                        f"No variable of type {entity_type} found in relation's variable_type_map."
                    )

                prefixed_id_column = f"{entity_type}__{ID_COLUMN}"

                # Semi-join: keep only rows in base_df whose IDs match filtered entities
                filtered_df = base_df[
                    base_df[base_entity_id_column].isin(
                        filtered_entity_df[prefixed_id_column]
                    )
                ]

                # Return only ID columns corresponding to variables, not attribute columns
                # Use column_names if specified, otherwise use variable_map values
                if self.column_names:
                    columns_to_keep = [
                        col
                        for col in self.column_names
                        if col in filtered_df.columns
                    ]
                    filtered_df = filtered_df[columns_to_keep]
                elif self.variable_map:
                    columns_to_keep = [
                        col
                        for col in self.variable_map.values()
                        if col in filtered_df.columns
                    ]
                    filtered_df = filtered_df[columns_to_keep]

                return filtered_df

            case _:
                raise NotImplementedError(
                    f"Condition type {type(self.condition)} not implemented yet."
                )
