version: "1.0"

sources:
  entities:
    - id: us_nodes
      uri: "file:///data/persons.csv"
      entity_type: Location
      id_col: id
      schema_hints:
        longitude: float
        latitude: float
        encoded_tags: STRING
        id: STRING
    - id: awards
      uri: "file:///data/persons.csv"
      entity_type: FederalGrant
      id_col: award_id
      schema_hints:
        1862_land_grant_college: STRING
        1890_land_grant_college: STRING
        1994_land_grant_college: STRING
        a76_fair_act_action: STRING
        a76_fair_act_action_code: STRING
        action_date: STRING
        action_date_fiscal_year: STRING
        action_type: STRING
        action_type_code: STRING
        airport_authority: STRING
        alaskan_native_corporation_owned_firm: STRING
        alaskan_native_servicing_institution: STRING
        american_indian_owned_business: STRING
        asian_pacific_american_owned_business: STRING
        award_id_piid: STRING
        award_or_idv_flag: STRING
        award_type: STRING
        award_type_code: STRING
        awarding_agency_code: STRING
        awarding_agency_name: STRING
        awarding_office_code: STRING
        awarding_office_name: STRING
        awarding_sub_agency_code: STRING
        awarding_sub_agency_name: STRING
        base_and_all_options_value: STRING
        base_and_exercised_options_value: STRING
        black_american_owned_business: STRING
        c8a_program_participant: STRING
        cage_code: STRING
        city_local_government: STRING
        clinger_cohen_act_planning: STRING
        clinger_cohen_act_planning_code: STRING
        commercial_item_acquisition_procedures: STRING
        commercial_item_acquisition_procedures_code: STRING
        community_developed_corporation_owned_firm: STRING
        community_development_corporation: STRING
        consolidated_contract: STRING
        consolidated_contract_code: STRING
        construction_wage_rate_requirements: STRING
        construction_wage_rate_requirements_code: STRING
        contingency_humanitarian_or_peacekeeping_operation: STRING
        contingency_humanitarian_or_peacekeeping_operation_code: STRING
        contract_award_unique_key: STRING
        contract_bundling: STRING
        contract_bundling_code: STRING
        contract_financing: STRING
        contract_financing_code: STRING
        contract_transaction_unique_key: STRING
        contracting_officers_determination_of_business_size: STRING
        contracting_officers_determination_of_business_size_code: STRING
        corporate_entity_not_tax_exempt: STRING
        corporate_entity_tax_exempt: STRING
        cost_accounting_standards_clause: STRING
        cost_accounting_standards_clause_code: STRING
        cost_or_pricing_data: STRING
        cost_or_pricing_data_code: STRING
        council_of_governments: STRING
        country_of_product_or_service_origin: STRING
        country_of_product_or_service_origin_code: STRING
        county_local_government: STRING
        current_total_value_of_award: STRING
        disaster_emergency_fund_codes_for_overall_award: STRING
        dod_acquisition_program_code: STRING
        dod_acquisition_program_description: STRING
        dod_claimant_program_code: STRING
        dod_claimant_program_description: STRING
        domestic_or_foreign_entity: STRING
        domestic_or_foreign_entity_code: STRING
        domestic_shelter: STRING
        dot_certified_disadvantage: STRING
        economically_disadvantaged_women_owned_small_business: STRING
        educational_institution: STRING
        emerging_small_business: STRING
        epa_designated_product: STRING
        epa_designated_product_code: STRING
        evaluated_preference: STRING
        evaluated_preference_code: STRING
        extent_competed: STRING
        extent_competed_code: STRING
        fair_opportunity_limited_sources: STRING
        fair_opportunity_limited_sources_code: STRING
        fed_biz_opps: STRING
        fed_biz_opps_code: STRING
        federal_accounts_funding_this_award: STRING
        federal_action_obligation: STRING
        federal_agency: STRING
        federally_funded_research_and_development_corp: STRING
        for_profit_organization: STRING
        foreign_funding: STRING
        foreign_funding_description: STRING
        foreign_government: STRING
        foreign_owned: STRING
        foundation: STRING
        funding_agency_code: STRING
        funding_agency_name: STRING
        funding_office_code: STRING
        funding_office_name: STRING
        funding_sub_agency_code: STRING
        funding_sub_agency_name: STRING
        government_furnished_property: STRING
        government_furnished_property_code: STRING
        highly_compensated_officer_1_amount: STRING
        highly_compensated_officer_1_name: STRING
        highly_compensated_officer_2_amount: STRING
        highly_compensated_officer_2_name: STRING
        highly_compensated_officer_3_amount: STRING
        highly_compensated_officer_3_name: STRING
        highly_compensated_officer_4_amount: STRING
        highly_compensated_officer_4_name: STRING
        highly_compensated_officer_5_amount: STRING
        highly_compensated_officer_5_name: STRING
        hispanic_american_owned_business: STRING
        hispanic_servicing_institution: STRING
        historically_black_college: STRING
        historically_underutilized_business_zone_hubzone_firm: STRING
        hospital_flag: STRING
        housing_authorities_public_tribal: STRING
        idv_type: STRING
        idv_type_code: STRING
        indian_tribe_federally_recognized: STRING
        information_technology_commercial_item_category: STRING
        information_technology_commercial_item_category_code: STRING
        inherently_governmental_functions: STRING
        inherently_governmental_functions_description: STRING
        initial_report_date: STRING
        inter_municipal_local_government: STRING
        interagency_contracting_authority: STRING
        interagency_contracting_authority_code: STRING
        international_organization: STRING
        interstate_entity: STRING
        joint_venture_economic_disadvantaged_women_owned_small_bus: STRING
        joint_venture_women_owned_small_business: STRING
        labor_standards: STRING
        labor_standards_code: STRING
        labor_surplus_area_firm: STRING
        last_modified_date: STRING
        limited_liability_corporation: STRING
        local_area_set_aside: STRING
        local_area_set_aside_code: STRING
        local_government_owned: STRING
        major_program: STRING
        manufacturer_of_goods: STRING
        materials_supplies_articles_equipment: STRING
        materials_supplies_articles_equipment_code: STRING
        minority_institution: STRING
        minority_owned_business: STRING
        modification_number: STRING
        multi_year_contract: STRING
        multi_year_contract_code: STRING
        multiple_or_single_award_idv: STRING
        multiple_or_single_award_idv_code: STRING
        municipality_local_government: STRING
        naics_code: STRING
        naics_description: STRING
        national_interest_action: STRING
        national_interest_action_code: STRING
        native_american_owned_business: STRING
        native_hawaiian_organization_owned_firm: STRING
        native_hawaiian_servicing_institution: STRING
        nonprofit_organization: STRING
        number_of_actions: STRING
        number_of_offers_received: STRING
        object_classes_funding_this_award: STRING
        obligated_amount_from_COVID-19_supplementals_for_overall_award: STRING
        obligated_amount_from_IIJA_supplemental_for_overall_award: STRING
        ordering_period_end_date: STRING
        organizational_type: STRING
        other_minority_owned_business: STRING
        other_not_for_profit_organization: STRING
        other_statutory_authority: STRING
        other_than_full_and_open_competition: STRING
        other_than_full_and_open_competition_code: STRING
        outlayed_amount_from_COVID-19_supplementals_for_overall_award: STRING
        outlayed_amount_from_IIJA_supplemental_for_overall_award: STRING
        parent_award_agency_id: STRING
        parent_award_agency_name: STRING
        parent_award_id_piid: STRING
        parent_award_modification_number: STRING
        parent_award_single_or_multiple: STRING
        parent_award_single_or_multiple_code: STRING
        parent_award_type: STRING
        parent_award_type_code: STRING
        partnership_or_limited_liability_partnership: STRING
        performance_based_service_acquisition: STRING
        performance_based_service_acquisition_code: STRING
        period_of_performance_current_end_date: STRING
        period_of_performance_potential_end_date: STRING
        period_of_performance_start_date: STRING
        place_of_manufacture: STRING
        place_of_manufacture_code: STRING
        planning_commission: STRING
        port_authority: STRING
        potential_total_value_of_award: STRING
        price_evaluation_adjustment_preference_percent_difference: STRING
        primary_place_of_performance_city_name: STRING
        primary_place_of_performance_country_code: STRING
        primary_place_of_performance_country_name: STRING
        primary_place_of_performance_county_name: STRING
        primary_place_of_performance_state_code: STRING
        primary_place_of_performance_state_name: STRING
        primary_place_of_performance_zip_4: STRING
        prime_award_base_transaction_description: STRING
        prime_award_transaction_place_of_performance_cd_current: STRING
        prime_award_transaction_place_of_performance_cd_original: STRING
        prime_award_transaction_place_of_performance_county_fips_code: STRING
        prime_award_transaction_place_of_performance_state_fips_code: STRING
        prime_award_transaction_recipient_cd_current: STRING
        prime_award_transaction_recipient_cd_original: STRING
        prime_award_transaction_recipient_county_fips_code: STRING
        prime_award_transaction_recipient_state_fips_code: STRING
        private_university_or_college: STRING
        product_or_service_code: STRING
        product_or_service_code_description: STRING
        program_acronym: STRING
        program_activities_funding_this_award: STRING
        purchase_card_as_payment_method: STRING
        purchase_card_as_payment_method_code: STRING
        receives_contracts: STRING
        receives_contracts_and_financial_assistance: STRING
        receives_financial_assistance: STRING
        recipient_address_line_1: STRING
        recipient_address_line_2: STRING
        recipient_city_name: STRING
        recipient_country_code: STRING
        recipient_country_name: STRING
        recipient_county_name: STRING
        recipient_doing_business_as_name: STRING
        recipient_duns: STRING
        recipient_fax_number: STRING
        recipient_name: STRING
        recipient_name_raw: STRING
        recipient_parent_duns: STRING
        recipient_parent_name: STRING
        recipient_parent_name_raw: STRING
        recipient_parent_uei: STRING
        recipient_phone_number: STRING
        recipient_state_code: STRING
        recipient_state_name: STRING
        recipient_uei: STRING
        recipient_zip_4_code: STRING
        recovered_materials_sustainability: STRING
        recovered_materials_sustainability_code: STRING
        research: STRING
        research_code: STRING
        sam_exception: STRING
        sam_exception_description: STRING
        sba_certified_8a_joint_venture: STRING
        school_district_local_government: STRING
        school_of_forestry: STRING
        sea_transportation: STRING
        sea_transportation_code: STRING
        self_certified_small_disadvantaged_business: STRING
        service_disabled_veteran_owned_business: STRING
        simplified_procedures_for_certain_commercial_items: STRING
        simplified_procedures_for_certain_commercial_items_code: STRING
        small_agricultural_cooperative: STRING
        small_business_competitiveness_demonstration_program: STRING
        small_disadvantaged_business: STRING
        sole_proprietorship: STRING
        solicitation_date: STRING
        solicitation_identifier: STRING
        solicitation_procedures: STRING
        solicitation_procedures_code: STRING
        state_controlled_institution_of_higher_learning: STRING
        subchapter_scorporation: STRING
        subcontinent_asian_asian_indian_american_owned_business: STRING
        subcontracting_plan: STRING
        subcontracting_plan_code: STRING
        the_ability_one_program: STRING
        total_dollars_obligated: STRING
        total_outlayed_amount_for_overall_award: STRING
        township_local_government: STRING
        transaction_description: STRING
        transaction_number: STRING
        transit_authority: STRING
        treasury_accounts_funding_this_award: STRING
        tribal_college: STRING
        tribally_owned_firm: STRING
        type_of_contract_pricing: STRING
        type_of_contract_pricing_code: STRING
        type_of_idc: STRING
        type_of_idc_code: STRING
        type_of_set_aside: STRING
        type_of_set_aside_code: STRING
        undefinitized_action: STRING
        undefinitized_action_code: STRING
        us_federal_government: STRING
        us_government_entity: STRING
        us_local_government: STRING
        us_state_government: STRING
        us_tribal_government: STRING
        usaspending_permalink: STRING
        veteran_owned_business: STRING
        veterinary_college: STRING
        veterinary_hospital: STRING
        woman_owned_business: STRING
        women_owned_small_business: STRING
  relationships:
    - id: employment
      uri: "file:///data/employment.csv"
      relationship_type: WORKS_FOR
      source_col: person_id
      target_col: company_id
      schema_hints:
        person_id: INTEGER
        company_id: INTEGER
        start_date: DATE
