"""
API request/response models auto-generated by generate_models.py.
DO NOT EDIT — regenerate with: make generate-models
"""

from typing import Optional

from pydantic import BaseModel

from fastopendata.graph_models import County, PUMA, State, Tract


class StructuredAddress(BaseModel):
    street_address_1: Optional[str] = None
    street_address_2: Optional[str] = None
    city: Optional[str] = None
    zip_code: Optional[str] = None


class FastOpenDataRequest(BaseModel):
    free_form_address: Optional[str] = None
    structured_address: Optional[StructuredAddress] = None


class FastOpenDataPayload(BaseModel):
    county: County = County()
    puma: PUMA = PUMA()
    state: State = State()
    tract: Tract = Tract()


class Metadata(BaseModel):
    request: FastOpenDataRequest
    success: bool
    payload: FastOpenDataPayload


class FastOpenDataResponse(BaseModel):
    metadata: Metadata
    payload: FastOpenDataPayload
