"""Pipeline utilities bridging fastopendata processing to pycypher graphs.

Provides :class:`GraphPipeline` — a builder that collects processed data
from streaming operators, batch DataFrames, or incremental views and
materializes them into a :class:`~pycypher.relational_models.Context`
ready for Cypher queries via :class:`~pycypher.star.Star`.

Example::

    from fastopendata.pipeline import GraphPipeline

    ctx = (
        GraphPipeline()
        .add_entity_dataframe("Person", people_df, id_col="person_id")
        .add_entity_dataframe("City", cities_df, id_col="city_id")
        .add_relationship_dataframe(
            "LIVES_IN", lives_in_df,
            source_col="person_id", target_col="city_id",
        )
        .build_context()
    )

    star = Star(ctx)
    result = star.execute_query("MATCH (p:Person)-[:LIVES_IN]->(c:City) RETURN p.name, c.name")

For streaming pipelines, records can be ingested incrementally::

    pipeline = GraphPipeline()
    pipeline.add_entity_records("Sensor", [
        {"__ID__": 1, "type": "temperature", "location": "building_a"},
        {"__ID__": 2, "type": "humidity", "location": "building_b"},
    ])
    pipeline.add_entity_records("Reading", [
        {"__ID__": 100, "sensor_id": 1, "value": 22.5, "timestamp": 1000.0},
    ])
    ctx = pipeline.build_context()

.. versionadded:: 0.0.2
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

import pandas as pd
from pycypher.ingestion.context_builder import ContextBuilder
from pycypher.relational_models import Context
from pycypher.star import Star

from fastopendata.schema_evolution.lineage import LineageEdge, LineageGraph, LineageNode, NodeType
from fastopendata.schema_evolution.registry import SchemaRegistry
from fastopendata.schema_evolution.schema import FieldSchema, FieldType, TableSchema
from fastopendata.streaming.core import StreamRecord
from fastopendata.streaming.views import IncrementalView

_logger = logging.getLogger(__name__)

# When ``GraphPipeline.build_context``/``.build_star`` is called with the
# default ``backend="auto"`` and the total number of entity rows across the
# pipeline exceeds this threshold, the backend is promoted to ``"duckdb"``.
# DuckDB's columnar engine handles national-scale OSM/contracts data far
# better than pandas; the ~500K row line was picked as the rough point at
# which pandas joins start visibly slowing down on a developer laptop.
# Override per-call by passing a non-"auto" backend explicitly, or override
# globally by setting ``GraphPipeline.DUCKDB_AUTO_THRESHOLD`` on a subclass.
_LARGE_DATASET_THRESHOLD = 500_000

# Backwards-compatible alias kept in case anything inside the package
# imported the original name.
_DUCKDB_AUTO_THRESHOLD = _LARGE_DATASET_THRESHOLD

# ACS PUMS person records — only a handful of demographic fields are useful
# for graph queries, but the source CSV ships with 500+ columns. Limit the
# read with ``usecols`` to keep load time bounded.
_ACS_PUMS_COLS = [
    "SERIALNO", "PUMA", "STATE", "AGEP", "SEX", "RAC1P",
    "SCHL", "ESR", "PINCP", "WAGP", "WKHP", "MIL", "HISP",
]

# Possible filenames the ACS PUMS person CSV may be extracted to. Snakemake
# rules and the dataset config use ``psam_pus.csv``; the other names cover
# manual extractions of the 1-year and 5-year archives.
_ACS_PUMS_FILES = ["psam_pus.csv", "psam_pus_1_year.csv", "psam_pus_5_year.csv"]

# Datasets handled by the dedicated ACS PUMS loading branch — skip these in
# the generic CSV loop to avoid loading 500+ columns or double-registering
# them under an autogenerated entity type.
_ACS_PUMS_DATASETS = frozenset({
    "acs_pums_1yr_persons",
    "acs_pums_5yr_persons",
})

# CJARS 2022 county job offers — small CSV (~25 MB) with county-level job
# opportunity statistics. Loaded as a dedicated ``CountyJobOffers`` entity
# (instead of an autogenerated ``Cjars2022`` from the generic loop) so the
# semantic name carries through to Cypher queries.
_CJARS_FILES = ["cjars_joe_2022_co.csv"]

_CJARS_DATASETS = frozenset({"cjars_2022"})

# FIPS columns in the CJARS CSV that pandas would otherwise read as int and
# silently strip leading zeros (e.g. Alabama county FIPS "01001" → 1001).
_CJARS_FIPS_COLS = ("county_fips", "state_fips")

# OpenStreetMap U.S. node extract — produced by ``extract_osm_nodes.py``.
# The full file is ~10 GB / 500M+ rows so loading via pandas would OOM most
# dev machines. We load via DuckDB with column projection + LIMIT pushdown,
# which streams the CSV without materializing it in pandas memory first.
_OSM_FILES = ["united_states_nodes.csv"]
_OSM_COLS = ("id", "longitude", "latitude", "encoded_tags")

# Default row cap for OSM loading in dev/test environments. Production
# callers can pass ``max_rows=None`` (the explicit signal "load everything")
# but ordinary ``load_available_datasets()`` invocations get capped here so
# OSM never accidentally tries to fit 500M rows in RAM.
_OSM_DEFAULT_MAX_ROWS = 100_000

_OSM_DATASETS = frozenset({"osm_us"})

# Mapping from pandas dtypes to schema FieldTypes
_DTYPE_MAP: dict[str, FieldType] = {
    "int64": FieldType.INTEGER,
    "int32": FieldType.INTEGER,
    "float64": FieldType.FLOAT,
    "float32": FieldType.FLOAT,
    "bool": FieldType.BOOLEAN,
    "object": FieldType.STRING,
    "string": FieldType.STRING,
    "datetime64[ns]": FieldType.TIMESTAMP,
}


def _schema_from_dataframe(name: str, df: pd.DataFrame) -> TableSchema:
    """Infer a :class:`TableSchema` from a DataFrame's dtypes."""
    fields: list[FieldSchema] = []
    for col in df.columns:
        dtype_str = str(df[col].dtype)
        field_type = _DTYPE_MAP.get(dtype_str, FieldType.STRING)
        has_nulls = bool(df[col].isna().any())
        fields.append(FieldSchema(name=col, field_type=field_type, nullable=has_nulls))
    return TableSchema(name=name, fields=tuple(fields))


def _load_shapefile_as_entity(
    filepath: Path,
    entity_type: str,
    id_col: str,
) -> pd.DataFrame | None:
    """Load a TIGER/Line shapefile as a plain DataFrame (geometry dropped).

    Reads ``filepath`` with geopandas, drops the ``geometry`` column, and
    returns a plain pandas DataFrame suitable for adding to a
    :class:`GraphPipeline` as an entity table.

    Parameters
    ----------
    filepath:
        Path to the ``.shp`` file (sibling ``.dbf``/``.shx``/``.prj``
        files must be present).
    entity_type:
        Entity label this shapefile represents (used only for logging).
    id_col:
        Expected primary-key column name (used only for logging; the
        caller is responsible for passing this to ``add_entity_dataframe``).

    Returns
    -------
    pandas.DataFrame or None
        The shapefile's attribute table without geometry, or *None* if
        geopandas is not installed (a warning is logged in that case).

    """
    try:
        import geopandas as gpd
    except ImportError:
        _logger.warning(
            "geopandas is not installed; cannot load shapefile %s as %s. "
            "Install with: pip install geopandas",
            filepath,
            entity_type,
        )
        return None

    gdf = gpd.read_file(filepath)
    df = pd.DataFrame(gdf.drop(columns="geometry", errors="ignore"))
    _logger.debug(
        "Loaded shapefile %s: %d rows, id_col=%s, entity_type=%s",
        filepath,
        len(df),
        id_col,
        entity_type,
    )
    return df


class GraphPipeline:
    """Collects data from multiple sources and builds a pycypher Context.

    Supports three ingestion patterns:

    1. **Batch** — add entire DataFrames via :meth:`add_entity_dataframe`
       and :meth:`add_relationship_dataframe`.
    2. **Record-level** — add lists of dicts via :meth:`add_entity_records`
       and :meth:`add_relationship_records` (convenient for streaming
       pipelines that produce records one at a time).
    3. **Streaming views** — add an :class:`IncrementalView` via
       :meth:`add_entity_from_view`, which snapshots the current
       accumulated state of a streaming view.

    All methods return ``self`` for chaining.
    """

    def __init__(
        self,
        schema_registry: SchemaRegistry | None = None,
    ) -> None:
        self._entity_frames: dict[str, pd.DataFrame] = {}
        self._relationship_frames: dict[
            str, tuple[pd.DataFrame, str, str]
        ] = {}
        self._entity_id_cols: dict[str, str | None] = {}
        self._schema_registry = schema_registry
        self._lineage = LineageGraph()

    # ── Batch ingestion ──────────────────────────────────────────────

    def add_entity_dataframe(
        self,
        entity_type: str,
        df: pd.DataFrame,
        *,
        id_col: str | None = None,
    ) -> GraphPipeline:
        """Register an entity type from a pandas DataFrame.

        Parameters
        ----------
        entity_type:
            The entity label (e.g. ``"Person"``).
        df:
            DataFrame containing entity data.
        id_col:
            Column to use as ``__ID__``.  Defaults to auto-generated IDs.

        """
        if self._schema_registry is not None and not df.empty:
            schema = _schema_from_dataframe(entity_type, df)
            existing = self._schema_registry.get_latest(entity_type)
            if existing is not None:
                compat = self._schema_registry.check_compatibility(
                    entity_type, schema
                )
                if not compat.compatible:
                    raise ValueError(
                        f"Schema for '{entity_type}' is incompatible with "
                        f"registered version {existing.version}: "
                        f"{[str(v) for v in compat.violations]}"
                    )
            self._schema_registry.register(schema)
            _logger.info(
                "Schema registered for %s (version %d, %d fields)",
                entity_type,
                schema.version,
                len(schema.fields),
            )

        self._entity_frames[entity_type] = df
        self._entity_id_cols[entity_type] = id_col
        self._lineage.add_node(LineageNode(
            node_id=f"entity:{entity_type}",
            node_type=NodeType.SOURCE,
            name=entity_type,
            metadata={"rows": str(len(df)), "columns": str(len(df.columns))},
        ))
        return self

    def add_relationship_dataframe(
        self,
        relationship_type: str,
        df: pd.DataFrame,
        *,
        source_col: str,
        target_col: str,
    ) -> GraphPipeline:
        """Register a relationship type from a pandas DataFrame.

        Parameters
        ----------
        relationship_type:
            The relationship label (e.g. ``"KNOWS"``).
        df:
            DataFrame containing relationship data.
        source_col:
            Column holding source node IDs.
        target_col:
            Column holding target node IDs.

        """
        self._relationship_frames[relationship_type] = (
            df,
            source_col,
            target_col,
        )
        # Track lineage: relationship node + edges to source/target entities
        rel_node_id = f"relationship:{relationship_type}"
        self._lineage.add_node(LineageNode(
            node_id=rel_node_id,
            node_type=NodeType.TRANSFORM,
            name=relationship_type,
            metadata={
                "rows": str(len(df)),
                "source_col": source_col,
                "target_col": target_col,
            },
        ))
        # Link source entity → relationship if the entity is already registered
        for entity_type in self._entity_frames:
            entity_node_id = f"entity:{entity_type}"
            if self._lineage.get_node(entity_node_id):
                self._lineage.add_edge(LineageEdge(
                    source_id=entity_node_id,
                    target_id=rel_node_id,
                    transformation=f"{entity_type} → {relationship_type}",
                ))
        return self

    # ── Record-level ingestion ───────────────────────────────────────

    def add_entity_records(
        self,
        entity_type: str,
        records: list[dict[str, Any]],
        *,
        id_col: str | None = None,
    ) -> GraphPipeline:
        """Register an entity type from a list of record dicts.

        Parameters
        ----------
        entity_type:
            The entity label.
        records:
            List of dicts, each representing one entity.
        id_col:
            Column to use as ``__ID__``.

        """
        df = pd.DataFrame(records)
        return self.add_entity_dataframe(entity_type, df, id_col=id_col)

    def add_relationship_records(
        self,
        relationship_type: str,
        records: list[dict[str, Any]],
        *,
        source_col: str,
        target_col: str,
    ) -> GraphPipeline:
        """Register a relationship type from a list of record dicts.

        Parameters
        ----------
        relationship_type:
            The relationship label.
        records:
            List of dicts, each representing one relationship.
        source_col:
            Key in each dict holding the source node ID.
        target_col:
            Key in each dict holding the target node ID.

        """
        df = pd.DataFrame(records)
        return self.add_relationship_dataframe(
            relationship_type,
            df,
            source_col=source_col,
            target_col=target_col,
        )

    # ── Streaming view ingestion ─────────────────────────────────────

    def add_entity_from_view(
        self,
        entity_type: str,
        view: IncrementalView,
        *,
        id_col: str | None = None,
    ) -> GraphPipeline:
        """Snapshot an :class:`IncrementalView` as an entity table.

        Takes the current accumulated records from a streaming view
        and registers them as an entity type.  The view's record values
        become the DataFrame columns.

        Parameters
        ----------
        entity_type:
            The entity label.
        view:
            An IncrementalView whose accumulated records will be
            snapshotted.
        id_col:
            Column to use as ``__ID__``.

        """
        records = list(view.snapshot.values())
        if not records:
            df = pd.DataFrame()
        else:
            df = pd.DataFrame(records)
        return self.add_entity_dataframe(entity_type, df, id_col=id_col)

    def add_entity_from_stream_records(
        self,
        entity_type: str,
        records: list[StreamRecord],
        *,
        id_col: str | None = None,
    ) -> GraphPipeline:
        """Register an entity type from a list of :class:`StreamRecord` objects.

        Extracts the ``value`` dict from each StreamRecord.

        Parameters
        ----------
        entity_type:
            The entity label.
        records:
            StreamRecord objects from a streaming pipeline.
        id_col:
            Column to use as ``__ID__``.

        """
        dicts = [r.value for r in records]
        if not dicts:
            df = pd.DataFrame()
        else:
            df = pd.DataFrame(dicts)
        return self.add_entity_dataframe(entity_type, df, id_col=id_col)

    # ── Context building ─────────────────────────────────────────────

    #: Threshold (total entity-row count) above which ``backend="auto"`` is
    #: promoted to ``"duckdb"``. Override on a subclass (or set on an
    #: instance) to change the policy for a given pipeline.
    DUCKDB_AUTO_THRESHOLD: int = _LARGE_DATASET_THRESHOLD

    def _total_entity_rows(self) -> int:
        """Sum of row counts across all registered entity DataFrames."""
        return sum(len(df) for df in self._entity_frames.values())

    def _resolve_backend(self, backend: str) -> str:
        """Apply the auto-promotion rule to a caller-supplied backend hint.

        ``"auto"`` is promoted to ``"duckdb"`` when the pipeline holds more
        than :attr:`DUCKDB_AUTO_THRESHOLD` total entity rows; otherwise
        ``"auto"`` is returned unchanged so the downstream context can do
        its own backend selection. Any explicit backend (``"pandas"``,
        ``"duckdb"``, ``"polars"``) is returned as-is — explicit caller
        intent always wins.
        """
        if backend != "auto":
            return backend

        total_rows = self._total_entity_rows()
        if total_rows > self.DUCKDB_AUTO_THRESHOLD:
            _logger.info(
                "Auto-selecting DuckDB backend: %d total entity rows "
                "exceeds threshold of %d",
                total_rows,
                self.DUCKDB_AUTO_THRESHOLD,
            )
            return "duckdb"
        return "auto"

    def build_context(self, backend: str = "auto") -> Context:
        """Assemble all registered data into a pycypher Context.

        Parameters
        ----------
        backend:
            Backend engine hint — ``"auto"`` (default), ``"pandas"``,
            ``"duckdb"``, or ``"polars"``. When ``"auto"`` and the total
            number of entity rows exceeds
            :attr:`DUCKDB_AUTO_THRESHOLD` (default 500 000), the backend
            is automatically promoted to ``"duckdb"``. Pass an explicit
            backend name to override.

        Returns
        -------
        Context
            A fully populated context ready for use with
            :class:`~pycypher.star.Star`.

        """
        backend = self._resolve_backend(backend)
        builder = ContextBuilder()

        for entity_type, df in self._entity_frames.items():
            id_col = self._entity_id_cols.get(entity_type)
            builder.add_entity(entity_type, df, id_col=id_col)

        for rel_type, (
            df,
            source_col,
            target_col,
        ) in self._relationship_frames.items():
            builder.add_relationship(
                rel_type,
                df,
                source_col=source_col,
                target_col=target_col,
            )

        # Finalize lineage: add Context sink with edges from all sources
        context_node_id = "context:pycypher"
        if not self._lineage.get_node(context_node_id):
            self._lineage.add_node(LineageNode(
                node_id=context_node_id,
                node_type=NodeType.SINK,
                name="PycypherContext",
                metadata={
                    "entity_types": str(len(self._entity_frames)),
                    "relationship_types": str(len(self._relationship_frames)),
                },
            ))
            for entity_type in self._entity_frames:
                node_id = f"entity:{entity_type}"
                if self._lineage.get_node(node_id):
                    self._lineage.add_edge(LineageEdge(
                        source_id=node_id,
                        target_id=context_node_id,
                        transformation="build_context",
                    ))
            for rel_type in self._relationship_frames:
                node_id = f"relationship:{rel_type}"
                if self._lineage.get_node(node_id):
                    self._lineage.add_edge(LineageEdge(
                        source_id=node_id,
                        target_id=context_node_id,
                        transformation="build_context",
                    ))

        return builder.build(backend=backend)

    def build_star(self, backend: str = "auto") -> Star:
        """Build a :class:`~pycypher.star.Star` query engine from the pipeline data.

        Parameters
        ----------
        backend:
            Backend engine hint — ``"auto"`` (default), ``"pandas"``,
            ``"duckdb"``, or ``"polars"``. When ``"auto"`` and the total
            number of entity rows exceeds
            :attr:`DUCKDB_AUTO_THRESHOLD` (default 500 000), the backend
            is automatically promoted to ``"duckdb"`` (delegated to
            :meth:`build_context`). Pass an explicit backend to override.

        Returns
        -------
        Star
            A query engine ready to execute Cypher queries.

        """
        return Star(self.build_context(backend=backend))

    # ── Inspection ───────────────────────────────────────────────────

    @property
    def lineage(self) -> LineageGraph:
        """Return the data lineage graph tracking pipeline data flow."""
        return self._lineage

    @property
    def entity_types(self) -> list[str]:
        """Return registered entity type names."""
        return list(self._entity_frames.keys())

    @property
    def relationship_types(self) -> list[str]:
        """Return registered relationship type names."""
        return list(self._relationship_frames.keys())

    def entity_count(self, entity_type: str) -> int:
        """Return the number of entities of the given type."""
        df = self._entity_frames.get(entity_type)
        return len(df) if df is not None else 0

    def relationship_count(self, relationship_type: str) -> int:
        """Return the number of relationships of the given type."""
        entry = self._relationship_frames.get(relationship_type)
        return len(entry[0]) if entry is not None else 0


def load_available_datasets(
    data_dir: Path | None = None,
    *,
    max_rows: int | None = None,
) -> GraphPipeline:
    """Discover and load available CSV datasets from the data directory.

    Scans the configured data directory for CSV output files listed in
    ``config.datasets`` and loads each one as an entity type in a
    :class:`GraphPipeline`.  Datasets whose output files do not exist
    (i.e. not yet downloaded via Snakemake) are silently skipped.

    Parameters
    ----------
    data_dir:
        Override the data directory from config. If *None*, uses
        ``config.data_dir``.
    max_rows:
        Optional row limit per dataset (useful for development/preview).

    Returns
    -------
    GraphPipeline
        A pipeline with all discovered datasets loaded as entity types.

    """
    from fastopendata.config import config

    if data_dir is None:
        data_dir = config.data_path
    else:
        data_dir = Path(data_dir)

    pipeline = GraphPipeline()
    loaded = 0

    for name, dataset in config.datasets.items():
        if not dataset.output_file:
            continue

        # ACS PUMS person CSVs have 500+ columns; load them in the
        # dedicated branch below with explicit column selection.
        if name in _ACS_PUMS_DATASETS:
            continue

        # CJARS county job offers — handled in a dedicated branch below
        # so it registers as ``CountyJobOffers`` (not the autogenerated
        # ``Cjars2022``) and gets ``dtype=str`` for FIPS columns.
        if name in _CJARS_DATASETS:
            continue

        # OSM U.S. nodes — 500M+ row file. Handled via the DuckDB branch
        # below to avoid loading the full CSV into pandas memory.
        if name in _OSM_DATASETS:
            continue

        filepath = data_dir / dataset.output_file
        if not filepath.exists():
            continue

        if dataset.format.upper() not in ("CSV", "PBF/CSV"):
            continue

        try:
            read_kwargs: dict[str, Any] = {}
            if max_rows is not None:
                read_kwargs["nrows"] = max_rows

            df = pd.read_csv(filepath, **read_kwargs)

            # Use dataset name as entity type, converting to PascalCase
            entity_type = name.replace("_", " ").title().replace(" ", "")

            # Auto-detect or generate an ID column
            id_col: str | None = None
            if "__ID__" in df.columns:
                id_col = "__ID__"

            pipeline.add_entity_dataframe(entity_type, df, id_col=id_col)
            loaded += 1
            _logger.info(
                "Loaded dataset %s: %d rows as entity type %s",
                name,
                len(df),
                entity_type,
            )
        except Exception:
            _logger.exception("Failed to load dataset %s from %s", name, filepath)

    # Second pass: discover and load TIGER/Line shapefiles as geographic
    # entities.  Per-state files are concatenated so each entity type is
    # registered exactly once even when multiple states are present.
    #
    # File pattern → (entity_type, id_col)
    shapefile_specs: list[tuple[str, str, str]] = [
        ("tl_2025_*_tract.shp", "CensusTract", "GEOID"),
        ("tl_2024_*_bg.shp", "BlockGroup", "GEOID"),
        ("tl_2024_*_puma20.shp", "Puma", "PUMACE20"),
    ]

    for pattern, entity_type, id_col in shapefile_specs:
        matches = sorted(data_dir.glob(pattern))
        if not matches:
            continue

        frames: list[pd.DataFrame] = []
        for shp_path in matches:
            try:
                df = _load_shapefile_as_entity(shp_path, entity_type, id_col)
            except Exception:
                _logger.exception(
                    "Failed to load shapefile %s as %s", shp_path, entity_type,
                )
                continue
            if df is None:
                # geopandas unavailable — warning already logged.  Bail out
                # of this entity type entirely; subsequent shapefiles will
                # also fail for the same reason.
                frames = []
                break
            frames.append(df)

        if not frames:
            continue

        if len(frames) == 1:
            combined = frames[0]
        else:
            combined = pd.concat(frames, ignore_index=True)

        try:
            pipeline.add_entity_dataframe(entity_type, combined, id_col=id_col)
            loaded += 1
            _logger.info(
                "Loaded %d shapefile(s) as entity type %s: %d rows",
                len(frames),
                entity_type,
                len(combined),
            )
        except Exception:
            _logger.exception(
                "Failed to register shapefile entity %s", entity_type,
            )

    # ── ACS PUMS person records ──────────────────────────────────────
    # Loaded outside the generic CSV loop so we can pass ``usecols`` —
    # the source file has 500+ columns and we only need ~13 demographic
    # fields. The 1-year file is preferred when both 1yr and 5yr are
    # present (first match wins to avoid double-registering Person).
    for pums_filename in _ACS_PUMS_FILES:
        pums_path = data_dir / pums_filename
        if not pums_path.exists():
            continue

        try:
            # Probe the header so we only request columns that exist.
            header_cols = pd.read_csv(pums_path, nrows=0).columns
            usecols = [c for c in _ACS_PUMS_COLS if c in header_cols]
            if not usecols:
                _logger.warning(
                    "ACS PUMS file %s has none of the expected columns; skipping",
                    pums_path,
                )
                break

            read_kwargs: dict[str, Any] = {"usecols": usecols}
            if max_rows is not None:
                read_kwargs["nrows"] = max_rows

            persons_df = pd.read_csv(pums_path, **read_kwargs)
            id_col_persons = "SERIALNO" if "SERIALNO" in persons_df.columns else None
            pipeline.add_entity_dataframe(
                "Person", persons_df, id_col=id_col_persons,
            )
            loaded += 1
            _logger.info(
                "Loaded ACS PUMS persons from %s: %d rows, %d columns as entity type Person",
                pums_filename,
                len(persons_df),
                len(persons_df.columns),
            )
            break  # First match wins.
        except Exception:
            _logger.exception("Failed to load ACS PUMS persons from %s", pums_path)

    # ── CJARS county job offers ──────────────────────────────────────
    # Small CSV (~25 MB) — load all columns, but force string dtype for
    # FIPS columns so leading-zero state codes (e.g. "01" Alabama) survive.
    for cjars_filename in _CJARS_FILES:
        cjars_path = data_dir / cjars_filename
        if not cjars_path.exists():
            continue

        try:
            # Probe the header so we apply dtype=str only to columns that
            # actually exist (defensive against schema drift).
            header_cols = pd.read_csv(cjars_path, nrows=0).columns
            dtype_map = {
                c: str for c in _CJARS_FIPS_COLS if c in header_cols
            }

            read_kwargs: dict[str, Any] = {"dtype": dtype_map} if dtype_map else {}
            if max_rows is not None:
                read_kwargs["nrows"] = max_rows

            cjars_df = pd.read_csv(cjars_path, **read_kwargs)
            id_col_cjars = (
                "county_fips" if "county_fips" in cjars_df.columns else None
            )
            pipeline.add_entity_dataframe(
                "CountyJobOffers", cjars_df, id_col=id_col_cjars,
            )
            loaded += 1
            _logger.info(
                "Loaded CJARS county job offers from %s: %d rows, %d columns "
                "as entity type CountyJobOffers",
                cjars_filename,
                len(cjars_df),
                len(cjars_df.columns),
            )
            break  # First match wins.
        except Exception:
            _logger.exception(
                "Failed to load CJARS county job offers from %s", cjars_path,
            )

    # ── OSM U.S. nodes ──────────────────────────────────────────────
    # The full file is 10 GB / 500M+ rows so we load via DuckDB's CSV
    # streaming reader with column projection + LIMIT pushdown rather than
    # ``pd.read_csv``. Default cap of 100K rows for dev; production callers
    # can pass ``max_rows=None`` (the explicit "load everything" signal) by
    # working around the ``load_available_datasets`` API — set
    # ``max_rows=0`` is treated as "use the OSM dev cap of 100K".
    osm_max_rows = (
        max_rows if (max_rows is not None and max_rows > 0)
        else _OSM_DEFAULT_MAX_ROWS
    )
    for osm_filename in _OSM_FILES:
        osm_path = data_dir / osm_filename
        if not osm_path.exists():
            continue

        try:
            import duckdb

            # Quote the path so spaces / special chars in the absolute path
            # don't break the SQL string. DuckDB accepts SQL-style quoting.
            sql_path = str(osm_path).replace("'", "''")
            col_list = ", ".join(_OSM_COLS)
            con = duckdb.connect(":memory:")
            try:
                osm_df = con.execute(
                    f"SELECT {col_list} FROM read_csv_auto('{sql_path}') "
                    f"LIMIT {osm_max_rows}"
                ).df()
            finally:
                con.close()

            id_col_osm = "id" if "id" in osm_df.columns else None
            pipeline.add_entity_dataframe(
                "OsmNode", osm_df, id_col=id_col_osm,
            )
            loaded += 1
            limit_note = (
                f"dev limit: {osm_max_rows}"
                if max_rows is None or max_rows == 0
                else f"caller limit: {max_rows}"
            )
            _logger.info(
                "Loaded OSM nodes from %s: %d rows, %d columns "
                "as entity type OsmNode (%s)",
                osm_filename,
                len(osm_df),
                len(osm_df.columns),
                limit_note,
            )
            break  # First match wins.
        except Exception:
            _logger.exception(
                "Failed to load OSM nodes from %s", osm_path,
            )

    # ── Derive relationships from loaded entities ────────────────────
    # All edges in the fastopendata graph are computed at load time by
    # joining FIPS / GEOID columns across entity tables. We inspect what
    # has been loaded and invoke the matching derive_* helpers; missing
    # entities cause silent skips so partial datasets still load cleanly.
    relationships_added = _derive_relationships(pipeline)

    _logger.info(
        "Loaded %d/%d available datasets, %d relationship type(s) derived",
        loaded,
        len(config.datasets),
        relationships_added,
    )
    return pipeline


def _derive_relationships(pipeline: GraphPipeline) -> int:
    """Run all available relationship derivations on a populated pipeline.

    Inspects ``pipeline._entity_frames`` and dispatches to the relevant
    ``derive_*`` helpers in :mod:`fastopendata.etl.relationship_derivation`.
    Each derivation is wrapped in its own try/except so a failure in one
    does not break the rest. Missing entities cause a silent skip with a
    debug log line.

    Parameters
    ----------
    pipeline:
        A GraphPipeline already populated with entity DataFrames.

    Returns
    -------
    int
        The number of relationship types successfully added.

    """
    from fastopendata.etl import relationship_derivation as _rd

    frames = pipeline._entity_frames  # noqa: SLF001 — internal coordination
    added = 0

    def _add_edges(rel_type: str, edges: pd.DataFrame) -> bool:
        if edges is None or edges.empty:
            _logger.debug("No %s edges derived; skipping", rel_type)
            return False
        pipeline.add_relationship_dataframe(
            rel_type, edges, source_col="__SOURCE__", target_col="__TARGET__",
        )
        _logger.info("Derived %d %s edges", len(edges), rel_type)
        return True

    # 1. CensusTract → State (IN_STATE)
    tracts_df = frames.get("CensusTract")
    states_df = frames.get("State")
    if tracts_df is not None and states_df is not None:
        try:
            edges = _rd.derive_tract_state_relationships(tracts_df, states_df)
            if _add_edges("IN_STATE", edges):
                added += 1
        except Exception:
            _logger.exception("Failed to derive IN_STATE relationships")
    else:
        _logger.debug(
            "Skipping IN_STATE derivation (CensusTract=%s, State=%s)",
            tracts_df is not None,
            states_df is not None,
        )

    # 2. CensusTract → Puma (MAPS_TO_PUMA via crosswalk)
    pumas_df = frames.get("Puma")
    crosswalk_df = frames.get("TractPumaCrosswalk")
    if (
        tracts_df is not None
        and pumas_df is not None
        and crosswalk_df is not None
    ):
        try:
            edges = _rd.derive_tract_puma_relationships(crosswalk_df)
            if _add_edges("MAPS_TO_PUMA", edges):
                added += 1
        except Exception:
            _logger.exception("Failed to derive MAPS_TO_PUMA relationships")
    else:
        _logger.debug(
            "Skipping MAPS_TO_PUMA derivation (CensusTract=%s, Puma=%s, "
            "TractPumaCrosswalk=%s)",
            tracts_df is not None,
            pumas_df is not None,
            crosswalk_df is not None,
        )

    # 3. CensusTract → BlockGroup (CONTAINS_BLOCK_GROUP)
    bg_df = frames.get("BlockGroup")
    if tracts_df is not None and bg_df is not None:
        try:
            edges = _rd.derive_tract_block_group_relationships(tracts_df, bg_df)
            if _add_edges("CONTAINS_BLOCK_GROUP", edges):
                added += 1
        except Exception:
            _logger.exception(
                "Failed to derive CONTAINS_BLOCK_GROUP relationships"
            )
    else:
        _logger.debug(
            "Skipping CONTAINS_BLOCK_GROUP derivation "
            "(CensusTract=%s, BlockGroup=%s)",
            tracts_df is not None,
            bg_df is not None,
        )

    # 4. Contract → State (PERFORMED_IN_STATE + AWARDED_IN_STATE)
    contracts_df = frames.get("Contract")
    if contracts_df is not None and states_df is not None:
        # Place-of-performance edges
        try:
            edges = _rd.derive_contract_state_relationships(
                contracts_df, states_df,
                fips_column=(
                    "prime_award_transaction_place_of_performance_state_fips_code"
                ),
            )
            if _add_edges("PERFORMED_IN_STATE", edges):
                added += 1
        except Exception:
            _logger.exception("Failed to derive PERFORMED_IN_STATE relationships")
        # Recipient-state edges
        try:
            edges = _rd.derive_contract_state_relationships(
                contracts_df, states_df,
                fips_column=(
                    "prime_award_transaction_recipient_state_fips_code"
                ),
            )
            if _add_edges("AWARDED_IN_STATE", edges):
                added += 1
        except Exception:
            _logger.exception("Failed to derive AWARDED_IN_STATE relationships")
    else:
        _logger.debug(
            "Skipping Contract→State derivations (Contract=%s, State=%s)",
            contracts_df is not None,
            states_df is not None,
        )

    # 5. Person → Puma (LIVES_IN_PUMA)
    persons_df = frames.get("Person")
    if persons_df is not None and pumas_df is not None:
        try:
            edges = _rd.derive_person_puma_relationships(persons_df, pumas_df)
            if _add_edges("LIVES_IN_PUMA", edges):
                added += 1
        except Exception:
            _logger.exception("Failed to derive LIVES_IN_PUMA relationships")
    else:
        _logger.debug(
            "Skipping LIVES_IN_PUMA derivation (Person=%s, Puma=%s)",
            persons_df is not None,
            pumas_df is not None,
        )

    # 6. CountyJobOffers → State (COUNTY_IN_STATE)
    counties_df = frames.get("CountyJobOffers")
    if counties_df is not None and states_df is not None:
        try:
            edges = _rd.derive_county_state_relationships(
                counties_df, states_df,
                county_fips_col="county_fips",
            )
            if _add_edges("COUNTY_IN_STATE", edges):
                added += 1
        except Exception:
            _logger.exception("Failed to derive COUNTY_IN_STATE relationships")
    else:
        _logger.debug(
            "Skipping COUNTY_IN_STATE derivation "
            "(CountyJobOffers=%s, State=%s)",
            counties_df is not None,
            states_df is not None,
        )

    return added
